### Part 1: Data Preprocessing

In [104]:
#import library and ignore warning 
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [105]:
#don't set the limited of display rows and columns of pd
pd.options.display.max_rows = None
pd.options.display.max_columns = None

In [106]:
#load the dataset from csv file
raw_csv_data = pd.read_csv('../data/raw/Absenteeism_data.csv')

#copy the data into dataframe
df = raw_csv_data.copy()

#read the header of file
df.head(10)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8

In [107]:
#lowercase & replace white space with underscore(_) for the columns name
df.columns = (df.columns
    .str.strip() #remove white space from head & tail
    .str.replace(' ', '_') #replace whitespace with _
    .str.lower()) #lowercase the columns name
df.head()

,id,reason_for_absence,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [108]:
#check number of rows and columns
df.shape

(700, 12)

In [109]:
#describe the dataset
df.describe(include='all')

,id,reason_for_absence,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
count,700.000000,700.000000,700,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
unique,NaN,NaN,432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,17/08/2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,17.951429,19.411429,NaN,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
std,11.028144,8.356292,NaN,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082
min,1.000000,0.000000,NaN,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,9.000000,13.000000,NaN,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,18.000000,23.000000,NaN,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,28.000000,27.000000,NaN,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,36.000000,28.000000,NaN,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000

In [110]:
#check datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         700 non-null    int64
 1   reason_for_absence         700 non-null    int64
 2   date                       700 non-null    object
 3   transportation_expense     700 non-null    int64
 4   distance_to_work           700 non-null    int64
 5   age                        700 non-null    int64
 6   daily_work_load_average    700 non-null    float64
 7   body_mass_index            700 non-null    int64
 8   education                  700 non-null    int64
 9   children                   700 non-null    int64
 10  pets                       700 non-null    int64
 11  absenteeism_time_in_hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

In [111]:
#drop the ID column
df = df.drop(columns='id', axis=1)
# df.drop(['ID], axis =1)
df.head()

,reason_for_absence,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [112]:
#min max and unique values of Reason for Absence

print(f'min: {df['reason_for_absence'].min()}')
print(f'max: {df['reason_for_absence'].max()}')
print(f'Unique Values: {df['reason_for_absence'].unique()}')
print(f'Sorted: {sorted(df['reason_for_absence'].unique())}')

min: 0
max: 28
Unique Values: [26  0 23  7 22 19  1 11 14 21 10 13 28 18 25 24  6 27 17  8 12  5  9 15
  4  3  2 16]
Sorted: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28)]

In [113]:
#get dummies()

reason_columns = pd.get_dummies(df['reason_for_absence'], dtype= int)
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [114]:
#sum each row in new columns call check
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1

In [115]:
#sum values in check column
reason_columns['check'].sum(axis=0)

np.int64(700)

In [116]:
#verify that all values in column check is 1
reason_columns['check'].unique()

array([1])

In [117]:
#drop the check column
reason_columns = reason_columns.drop(['check'], axis = 1)
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [118]:
reason_columns.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [119]:
#drop the first column which is number 0: unknwon reason of absense
reason_columns = pd.get_dummies(df['reason_for_absence'], drop_first=True, dtype=int)
reason_columns.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [120]:
#group the reason into same key characteristics
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

- Group 1: related to disease 1-14
- Group 2: related to pregnancy and give birth 15-17
- Group 3: poisoning or sign not elsewhere categorized 18-21
- Group 4: ligh reason of absenss 22-28

In [121]:
#classified the data
#loc[] is label-based [1, 2] 
#1: number of rows
#2: columns from the start to end
reason_columns.loc[:, '1':'14']

     1   2   3   4   5   6   7   8   9   10  11  12  13  14
0     0   0   0   0   0   0   0   0   0   0   0   0   0   0
1     0   0   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0   0   0
3     0   0   0   0   0   0   1   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0   0   0
5     0   0   0   0   0   0   0   0   0   0   0   0   0   0
6     0   0   0   0   0   0   0   0   0   0   0   0   0   0
7     0   0   0   0   0   0   0   0   0   0   0   0   0   0
8     0   0   0   0   0   0   0   0   0   0   0   0   0   0
9     0   0   0   0   0   0   0   0   0   0   0   0   0   0
10    1   0   0   0   0   0   0   0   0   0   0   0   0   0
11    1   0   0   0   0   0   0   0   0   0   0   0   0   0
12    0   0   0   0   0   0   0   0   0   0   1   0   0   0
13    0   0   0   0   0   0   0   0   0   0   1   0   0   0
14    0   0   0   0   0   0   0   0   0   0   0   0   0   0
15    0   0   0   0   0   0   0   0   0   0   0   0   0   1
16    0   0   0   0   0   0   0   0   0   0   0   0   0   0
17    0   0   0   0   0   0   0   0   0   0   0   0   0   0
18    0   0   0   0   0   0   0   0   0   0   1   0   0   0
19    0   0   0   0   0   0   0   0   0   0   0   0   0   0
20    0   0   0   0   0   0   0   0   0   1   0   0   0   0
21    0   0   0   0   0   0   0   0   0   0   1   0   0   0
22    0   0   0   0   0   0   0   0   0   0   0   0   1   0
23    0   0   0   0   0   0   0   0   0   0   0   0   0   0
24    0   0   0   0   0   0   0   0   0   0   0   0   0   0
25    0   0   0   0   0   0   0   0   0   0   0   0   0   0
26    0   0   0   0   0   0   0   0   0   0   0   0   0   0
27    0   0   0   0   0   0   0   0   0   0   0   0   0   0
28    0   0   0   0   0   0   0   0   0   0   0   0   0   0
29    0   0   0   0   0   0   0   0   0   0   0   0   0   0
30    0   0   0   0   0   0   0   0   0   0   0   0   0   0
31    0   0   0   0   0   0   0   0   0   0   0   0   0   0
32    0   0   0   0   0   0   0   0   0   0   0   0   0   0
33    0   0   0   0   0   0   0   0   0   0   0   0   0   0
34    0   0   0   0   0   0   0   0   0   0   0   0   0   0
35    0   0   0   0   0   0   0   0   0   0   0   0   0   0
36    0   0   0   0   0   0   0   0   0   0   0   0   0   0
37    0   0   0   0   0   0   0   0   0   0   1   0   0   0
38    0   0   0   0   0   0   0   0   0   0   0   0   0   0
39    0   0   0   0   0   0   0   0   0   0   0   0   0   0
40    0   0   0   0   0   0   0   0   0   0   0   0   0   0
41    0   0   0   0   0   0   0   0   0   0   0   0   0   0
42    0   0   0   0   0   0   0   0   0   0   0   0   0   0
43    0   0   0   0   0   0   0   0   0   0   0   0   0   0
44    0   0   0   0   0   0   0   0   0   0   0   0   0   0
45    0   0   0   0   0   0   0   0   0   0   0   0   0   0
46    0   0   0   0   0   0   0   0   0   0   0   0   0   0
47    0   0   0   0   0   0   0   0   0   0   0   0   0   0
48    0   0   0   0   0   0   0   0   0   0   0   0   0   0
49    0   0   0   0   0   0   0   0   0   0   0   0   0   1
50    0   0   0   0   0   0   0   0   0   0   0   0   0   0
51    0   0   0   0   0   0   0   0   0   0   0   0   0   0
52    0   0   0   0   0   0   0   0   0   0   0   0   0   0
53    0   0   0   0   0   0   0   0   0   0   0   0   0   0
54    0   0   0   0   0   0   0   0   0   0   0   0   0   0
55    0   0   0   0   0   0   0   0   0   0   0   0   0   0
56    0   0   0   0   0   0   0   0   0   0   0   0   0   0
57    0   0   0   0   0   0   0   0   0   0   0   0   0   0
58    0   0   0   0   0   0   0   0   0   0   0   0   0   0
59    0   0   0   0   0   0   0   0   0   0   0   0   0   0
60    0   0   0   0   0   0   0   0   0   0   0   0   0   0
61    0   0   0   0   0   0   0   0   0   0   0   0   0   0
62    0   0   0   0   0   0   0   0   0   0   0   0   0   0
63    0   0   0   0   0   0   0   0   0   0   0   0   0   0
64    0   0   0   0   0   0   0   0   0   0   0   0   0   0
65    0   0   0   0   0   0   0   0   0   0   0   0   0   0
66    0   0   0   0   0   0   0   0   0   0   0   0   0   0
67    0   0   0   0   0   0   0   0   0   0   0   0   0   0
68    0   0   0   0   0   0   0   0   0   0   0   0   0   0
69    0   0   0   0   0   0   0   0   0   0   0   0   0   0
70    0   0   0   0   0   0   0   0   0   0   0   0   0   0
71    0   0   0   0   0   0   0   0   0   0   0   0   0   0
72    0   0   0   0   0   0   0   0   0   0   0   0   0   0
73    0   0   0   0   0   0   0   0   0   0   0   0   0   0
74    0   0   0   0   0   0   0   0   0   0   0   0   0   0
75    0   0   0   0   0   0   0   0   0   0   0   0   0   1
76    0   0   0   0   0   0   0   0   0   0   0   0   0   0
77    0   0   0   0   0   0   0   0   0   0   0   0   0   0
78    0   0   0   0   0   0   0   0   0   0   0   0   0   0
79    0   0   0   0   0   0   0   0   0   0   0   0   0   0
80    0   0   0   0   0   0   0   0   0   0   0   0   0   0
81    0   0   0   0   0   0   0   0   0   0   0   0   0   0
82    0   0   0   0   0   0   0   0   0   0   0   0   1   0
83    0   0   0   0   0   0   0   0   0   0   0   0   0   0
84    0   0   0   0   0   0   0   0   0   0   0   0   0   0
85    0   0   0   0   0   0   0   0   0   1   0   0   0   0
86    0   0   0   0   0   0   0   0   0   0   0   0   0   0
87    0   0   0   0   0   0   0   0   0   0   0   0   0   1
88    0   0   0   0   0   0   0   0   0   0   0   0   0   0
89    0   0   0   0   0   1   0   0   0   0   0   0   0   0
90    0   0   0   0   0   0   0   0   0   0   0   0   0   0
91    0   0   0   0   0   0   0   0   0   0   0   0   0   0
92    0   0   0   0   0   0   0   0   0   0   0   0   1   0
93    0   0   0   0   0   0   0   0   0   0   0   0   0   0
94    0   0   0   0   0   0   0   0   0   0   0   0   0   0
95    0   0   0   0   0   0   0   0   0   0   0   0   0   0
96    0   0   0   0   0   0   1   0   0   0   0   0   0   0
97    0   0   0   0   0   0   0   0   0   0   0   0   0   0
98    0   0   0   0   0   0   0   0   0   0   0   0   0   0
99    0   0   0   0   0   0   0   0   0   0   0   0   0   0
100   0   0   0   0   0   0   0   0   0   0   0   0   0   0
101   0   0   0   0   0   0   0   0   0   0   0   0   0   0
102   0   0   0   0   0   0   0   0   0   0   0   0   0   0
103   0   0   0   0   0   0   0   0   0   0   0   0   0   0
104   0   0   0   0   0   0   0   0   0   0   0   0   0   0
105   0   0   0   0   0   0   0   0   0   0   0   0   0   0
106   0   0   0   0   0   0   0   0   0   0   0   0   0   0
107   0   0   0   0   0   0   0   0   0   0   0   0   0   0
108   0   0   0   0   0   0   0   0   0   0   0   0   0   0
109   0   0   0   0   0   0   0   0   0   0   0   0   0   0
110   0   0   0   0   0   0   0   0   0   0   0   0   0   0
111   0   0   0   0   0   0   0   0   0   0   0   0   0   0
112   0   0   0   0   0   0   0   0   0   0   0   0   0   0
113   0   0   0   0   0   0   0   0   0   0   0   0   0   0
114   0   0   0   0   0   0   0   0   0   0   0   0   0   0
115   0   0   0   0   0   0   0   0   0   0   0   0   0   0
116   0   0   0   0   0   0   0   0   0   0   0   0   0   0
117   0   0   0   0   0   0   0   0   0   0   0   0   0   0
118   0   0   0   0   0   0   0   0   0   0   0   0   0   0
119   0   0   0   0   0   0   0   0   0   0   0   0   0   0
120   0   0   0   0   0   0   0   0   0   0   0   0   0   0
121   0   0   0   0   0   0   0   0   0   0   0   0   0   0
122   0   0   0   0   0   0   0   0   0   0   0   0   0   0
123   0   0   0   0   0   0   0   0   0   0   0   0   0   0
124   0   0   0   0   0   0   0   0   0   0   0   0   0   0
125   0   0   0   0   0   0   0   0   0   0   0   0   0   0
126   0   0   0   0   0   0   0   0   0   0   0   0   0   0
127   0   0   0   0   0   0   0   0   0   0   0   0   0   0
128   0   0   0   0   0   0   0   0   0   0   0   0   0   0
129   0   0   0   0   0   0   0   0   0   0   0   0   0   0
130   0   0   0   0   0   0   0   0   0   0   0   0   0   0
131   0   0   0   0   0   0   0   0   0   0   0   0   0   0
132   0   0   0   0   0   0   0   0   0   0   0   0   0   0
133   0   0   0   0   0   0   0   0   0   0   0   0   0   0
134   0   0   0   0   0   0   0   0   0   0   0   0   0   0
135   0   0   0   0   0   0   0   0   0   0   0   0   0   0
136   0   0   0   0   0   0   0   0   0   0   0   0   0   0
137   0   0   0   0   0   0   0   0   0   0   0   0   0   0
138   1   0   0   0   0   0   0   0   0   0   0   0   0   0
139   0   0   0   0   0   0   0   0   0   0   1   0   0   0
140   0   0   0   0   0   0   0   0   0   0   0   0   0   0
141   0   0   0   0   0   0   0   0   0   0   0   0   0   0
142   0   0   0   0   0   0   0   0   0   0   0   0   0   0
143   0   0   0   0   0   0   0   0   0   0   0   0   0   0
144   0   0   0   0   0   0   0   0   0   0   1   0   0   0
145   1   0   0   0   0   0   0   0   0   0   0   0   0   0
146   0   0   0   0   0   0   0   0   0   0   0   0   0   0
147   0   0   0   0   0   0   0   0   0   0   0   0   0   0
148   0   0   0   0   0   0   0   0   0   0   0   0   0   0
149   0   0   0   0   0   0   0   0   0   0   0   0   0   0
150   0   0   0   0   0   0   0   0   0   0   0   0   0   0
151   0   0   0   0   0   0   0   0   0   0   0   0   0   0
152   0   0   0   0   0   0   0   0   0   0   0   0   0   0
153   0   0   0   0   0   0   0   0   0   0   0   0   0   0
154   0   0   0   0   0   0   0   0   0   0   0   0   0   0
155   0   0   0   0   0   0   0   0   0   0   0   0   0   0
156   0   0   0   0   0   0   0   0   0   0   0   0   0   0
157   0   0   0   0   0   0   0   0   0   0   0   0   0   0
158   0   0   0   0   0   0   0   0   0   0   0   0   0   0
159   0   0   0   0   0   0   0   0   0   0   0   0   0   0
160   0   0   0   0   0   0   0   0   0   0   0   0   1   0
161   0   0   0   0   0   0   0   0   0   0   0   0   1   0
162   0   0   0   0   0   0   0   0   0   0   0   0   0   1
163   0   0   0   0   0   0   0   0   0   0   0   0   1   0
164   0   0   0   0   0   0   0   0   0   0   1   0   0   0
165   1   0   0   0   0   0   0   0   0   0   0   0   0   0
166   0   0   0   0   0   0   0   0   0   0   0   0   0   0
167   0   0   0   0   0   0   0   0   0   0   0   0   1   0
168   0   0   0   0   0   1   0   0   0   0   0   0   0   0
169   0   0   0   0   0   0   0   1   0   0   0   0   0   0
170   0   0   0   0   0   0   0   0   0   0   0   0   0   0
171   0   0   0   0   0   0   0   0   0   0   0   0   0   0
172   0   0   0   0   0   0   0   0   0   0   0   0   0   1
173   0   0   0   0   0   0   0   0   0   0   0   0   1   0
174   0   0   0   0   0   0   0   0   0   0   0   0   0   0
175   0   0   0   0   0   0   0   0   0   0   1   0   0   0
176   0   0   0   0   0   0   0   0   0   0   0   0   1   0
177   0   0   0   0   0   0   0   0   0   0   1   0   0   0
178   0   0   0   0   0   0   0   0   0   0   1   0   0   0
179   0   0   0   0   0   0   0   0   0   0   0   0   1   0
180   0   0   0   0   0   0   0   0   0   0   0   0   0   1
181   0   0   0   0   0   0   0   0   0   0   0   0   0   0
182   0   0   0   0   0   0   0   0   0   0   0   0   0   1
183   0   0   0   0   0   0   0   0   0   0   0   0   0   0
184   0   0   0   0   0   0   0   0   0   0   0   0   0   0
185   0   0   0   0   0   0   0   0   0   0   0   0   0   0
186   0   0   0   0   0   0   0   0   0   0   0   0   0   0
187   0   0   0   0   0   0   0   0   0   0   0   0   1   0
188   0   0   0   0   0   0   0   0   0   0   0   0   0   0
189   0   0   0   0   0   0   0   0   0   0   0   0   0   0
190   0   0   0   0   0   0   0   0   0   0   0   0   0   0
191   0   0   0   0   0   0   0   0   0   0   0   0   1   0
192   0   0   0   0   0   0   0   0   0   0   0   0   0   0
193   0   0   0   0   0   0   0   0   0   0   0   0   0   0
194   0   0   0   0   0   0   0   0   0   0   0   0   0   1
195   0   0   0   0   0   0   0   0   0   0   0   0   0   0
196   0   0   0   0   0   0   0   0   0   0   0   0   0   0
197   0   0   0   0   0   0   0   0   0   0   0   0   0   0
198   0   0   0   0   0   0   0   0   0   0   0   0   0   0
199   0   0   0   0   0   0   0   0   0   0   0   1   0   0
200   0   0   0   0   0   0   0   0   0   0   0   0   0   0
201   0   0   0   0   0   0   0   0   0   0   0   0   1   0
202   0   0   0   0   0   0   1   0   0   0   0   0   0   0
203   0   0   0   0   0   0   0   0   0   0   0   0   0   0
204   0   0   0   0   0   0   0   0   0   0   0   0   1   0
205   0   0   0   0   0   0   0   0   0   0   0   0   0   0
206   0   0   0   0   0   0   0   0   0   0   0   0   0   0
207   0   0   0   0   0   0   0   0   0   0   0   0   0   0
208   0   0   0   0   0   0   0   0   0   0   0   0   0   0
209   0   0   0   0   0   0   1   0   0   0   0   0   0   0
210   0   0   0   0   0   0   0   0   0   0   0   0   0   0
211   0   0   0   0   0   0   0   0   0   0   0   1   0   0
212   0   0   0   0   0   0   0   0   0   0   0   0   1   0
213   0   0   0   0   0   0   0   0   0   0   0   0   0   0
214   0   0   0   0   0   0   0   0   0   0   0   0   0   0
215   0   0   0   0   0   0   0   0   0   0   0   0   0   0
216   0   0   0   0   0   0   0   0   0   0   0   0   0   0
217   0   0   0   0   0   0   0   0   0   0   1   0   0   0
218   0   0   0   0   0   0   0   0   0   0   0   0   1   0
219   0   0   0   0   0   0   0   0   0   0   0   0   0   0
220   0   0   0   0   0   0   0   0   0   0   0   0   0   0
221   0   0   0   0   0   0   0   0   0   0   0   0   0   0
222   0   0   0   0   0   0   0   0   0   1   0   0   0   0
223   0   0   0   0   0   0   0   0   0   0   0   0   0   0
224   0   0   0   0   0   0   0   0   0   1   0   0   0   0
225   0   0   0   0   0   0   0   0   0   0   1   0   0   0
226   0   0   0   0   0   0   0   0   0   0   0   0   0   0
227   0   0   0   0   0   0   0   0   0   1   0   0   0   0
228   0   0   0   0   0   0   0   0   0   0   0   0   1   0
229   0   0   0   0   0   0   0   0   0   0   0   0   1   0
230   0   0   0   0   0   0   0   0   0   0   0   0   0   0
231   0   0   0   0   0   0   0   0   0   0   0   0   1   0
232   0   0   0   0   0   0   0   0   0   0   0   0   0   0
233   0   0   0   0   0   0   0   0   0   0   1   0   0   0
234   0   0   0   0   0   0   0   0   0   0   0   0   0   0
235   0   0   0   0   0   0   0   0   0   0   0   0   0   0
236   0   0   0   0   0   0   0   0   0   0   0   0   0   0
237   1   0   0   0   0   0   0   0   0   0   0   0   0   0
238   0   0   0   0   1   0   0   0   0   0   0   0   0   0
239   0   0   0   0   0   0   0   0   0   0   0   0   0   0
240   0   0   0   0   0   0   0   0   0   0   0   0   0   0
241   0   0   0   0   0   0   0   0   0   0   0   0   0   0
242   0   0   0   0   0   0   0   0   0   0   0   0   0   0
243   1   0   0   0   0   0   0   0   0   0   0   0   0   0
244   1   0   0   0   0   0   0   0   0   0   0   0   0   0
245   0   0   0   0   0   0   0   0   0   0   0   0   0   0
246   0   0   0   0   0   0   0   0   0   0   0   0   0   0
247   0   0   0   0   0   0   0   0   0   0   0   0   0   0
248   0   0   0   0   0   0   0   0   0   0   0   0   0   0
249   0   0   0   0   0   0   0   0   0   0   0   0   0   0
250   0   0   0   0   0   0   0   0   0   0   0   0   0   0
251   0   0   0   0   0   0   0   0   0   0   0   0   0   0
252   0   0   0   0   0   0   0   0   0   0   0   0   0   0
253   0   0   0   0   0   0   0   0   0   0   0   0   0   0
254   0   0   0   0   0   0   0   0   0   0   0   0   0   0
255   0   0   0   0   0   0   0   0   0   0   0   0   0   0
256   0   0   0   0   0   0   0   0   0   0   0   0   1   0
257   0   0   0   0   0   0   0   0   0   0   0   0   0   1
258   0   0   0   0   0   0   0   0   0   0   0   0   0   0
259   0   0   0   0   0   0   0   0   0   0   0   0   0   0
260   0   0   0   0   0   0   0   0   0   0   0   0   0   0
261   0   0   0   0   0   0   0   0   0   0   1   0   0   0
262   0   0   0   0   0   0   0   0   0   0   0   0   0   0
263   0   0   0   0   0   0   0   0   0   0   0   0   1   0
264   0   0   0   0   0   0   0   0   0   0   0   0   0   0
265   0   0   0   0   0   0   0   0   0   0   0   0   0   0
266   0   0   0   0   0   0   0   0   0   0   0   0   0   0
267   0   0   0   0   0   0   0   0   0   0   0   0   0   0
268   0   0   0   0   0   0   0   1   0   0   0   0   0   0
269   0   0   0   0   0   1   0   0   0   0   0   0   0   0
270   0   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   0   0   0   0   0   0   0   0   0   0   0
272   0   0   0   0   0   0   0   0   0   0   0   0   0   0
273   0   0   0   0   0   0   0   0   0   0   0   0   0   0
274   0   0   0   0   0   0   0   0   1   0   0   0   0   0
275   0   0   0   0   0   0   0   0   0   0   0   0   0   0
276   0   0   0   0   0   0   0   0   0   0   0   0   0   0
277   0   0   0   0   0   0   0   0   0   0   0   0   0   0
278   0   0   0   0   0   0   0   0   0   0   0   0   1   0
279   0   0   0   0   0   0   0   0   1   0   0   0   0   0
280   0   0   0   0   0   0   0   0   0   0   0   0   0   0
281   0   0   0   0   0   0   0   0   0   0   0   0   0   0
282   0   0   0   0   0   0   0   0   0   0   0   0   0   0
283   0   0   0   0   0   0   0   0   0   0   0   0   0   0
284   0   0   0   0   0   0   0   0   0   0   0   0   0   0
285   0   0   0   0   0   0   0   0   0   0   0   0   0   0
286   0   0   0   0   0   0   0   0   0   0   0   0   0   0
287   0   0   0   0   0   0   1   0   0   0   0   0   0   0
288   0   0   0   0   0   0   0   0   0   0   0   0   1   0
289   0   0   0   0   0   0   0   0   0   0   0   0   0   0
290   0   0   0   0   0   0   0   0   0   0   0   0   0   0
291   0   0   0   0   0   0   0   0   0   0   0   0   0   0
292   0   0   0   0   0   0   0   0   0   0   0   0   0   0
293   0   0   0   0   0   0   0   0   0   0   0   0   0   0
294   0   0   0   0   0   0   0   0   0   0   0   0   0   0
295   1   0   0   0   0   0   0   0   0   0   0   0   0   0
296   0   0   0   0   0   0   1   0   0   0   0   0   0   0
297   0   0   0   0   0   0   0   0   0   0   0   0   0   0
298   0   0   0   0   0   0   0   0   0   0   0   0   0   0
299   1   0   0   0   0   0   0   0   0   0   0   0   0   0
300   0   0   0   0   0   0   0   0   0   0   0   0   0   0
301   0   0   0   0   0   0   0   0   0   0   0   0   0   0
302   0   0   0   0   0   0   0   0   0   0   0   0   0   0
303   0   0   0   0   0   0   0   0   0   0   0   0   0   0
304   0   0   0   0   0   0   0   0   0   0   0   0   0   0
305   0   0   0   0   0   0   0   0   0   0   0   0   0   0
306   0   0   0   0   0   0   0   0   0   0   0   0   0   0
307   0   0   0   0   0   0   0   0   0   0   0   0   0   0
308   0   0   0   0   0   0   0   0   0   0   0   0   0   0
309   0   0   0   0   0   0   0   0   0   0   0   0   0   0
310   0   0   0   0   0   0   0   0   0   1   0   0   0   0
311   0   0   0   0   0   0   0   0   0   0   0   0   0   0
312   0   0   0   0   0   0   0   0   0   0   0   0   0   0
313   0   0   0   0   0   0   0   0   0   0   0   0   0   0
314   1   0   0   0   0   0   0   0   0   0   0   0   0   0
315   0   0   0   0   0   0   1   0   0   0   0   0   0   0
316   0   0   0   0   0   0   0   0   0   0   0   0   0   0
317   0   0   0   0   0   0   0   0   0   0   1   0   0   0
318   0   0   0   0   0   0   0   0   0   0   0   0   0   0
319   0   0   0   0   0   1   0   0   0   0   0   0   0   0
320   0   0   0   0   0   0   0   0   0   0   0   0   0   0
321   0   0   0   0   0   0   0   0   0   0   0   0   0   0
322   1   0   0   0   0   0   0   0   0   0   0   0   0   0
323   0   0   0   0   0   0   0   0   0   0   1   0   0   0
324   0   0   0   0   0   0   0   0   0   0   0   0   0   0
325   0   0   0   0   0   0   0   0   0   0   0   0   0   0
326   0   0   0   0   0   0   0   0   0   0   0   0   0   0
327   0   0   0   0   0   0   0   0   0   0   1   0   0   0
328   0   0   0   0   0   0   0   0   0   0   0   0   0   0
329   0   0   0   0   0   0   0   0   0   0   0   0   0   0
330   0   0   0   0   0   0   0   0   0   0   0   0   1   0
331   0   0   0   0   0   0   0   0   0   0   0   1   0   0

In [122]:
#iloc using index base which mean that start from 0 to the len -1 of our dataset
reason_columns.iloc[:, 0:14]

     1   2   3   4   5   6   7   8   9   10  11  12  13  14
0     0   0   0   0   0   0   0   0   0   0   0   0   0   0
1     0   0   0   0   0   0   0   0   0   0   0   0   0   0
2     0   0   0   0   0   0   0   0   0   0   0   0   0   0
3     0   0   0   0   0   0   1   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   0   0   0   0   0   0   0
5     0   0   0   0   0   0   0   0   0   0   0   0   0   0
6     0   0   0   0   0   0   0   0   0   0   0   0   0   0
7     0   0   0   0   0   0   0   0   0   0   0   0   0   0
8     0   0   0   0   0   0   0   0   0   0   0   0   0   0
9     0   0   0   0   0   0   0   0   0   0   0   0   0   0
10    1   0   0   0   0   0   0   0   0   0   0   0   0   0
11    1   0   0   0   0   0   0   0   0   0   0   0   0   0
12    0   0   0   0   0   0   0   0   0   0   1   0   0   0
13    0   0   0   0   0   0   0   0   0   0   1   0   0   0
14    0   0   0   0   0   0   0   0   0   0   0   0   0   0
15    0   0   0   0   0   0   0   0   0   0   0   0   0   1
16    0   0   0   0   0   0   0   0   0   0   0   0   0   0
17    0   0   0   0   0   0   0   0   0   0   0   0   0   0
18    0   0   0   0   0   0   0   0   0   0   1   0   0   0
19    0   0   0   0   0   0   0   0   0   0   0   0   0   0
20    0   0   0   0   0   0   0   0   0   1   0   0   0   0
21    0   0   0   0   0   0   0   0   0   0   1   0   0   0
22    0   0   0   0   0   0   0   0   0   0   0   0   1   0
23    0   0   0   0   0   0   0   0   0   0   0   0   0   0
24    0   0   0   0   0   0   0   0   0   0   0   0   0   0
25    0   0   0   0   0   0   0   0   0   0   0   0   0   0
26    0   0   0   0   0   0   0   0   0   0   0   0   0   0
27    0   0   0   0   0   0   0   0   0   0   0   0   0   0
28    0   0   0   0   0   0   0   0   0   0   0   0   0   0
29    0   0   0   0   0   0   0   0   0   0   0   0   0   0
30    0   0   0   0   0   0   0   0   0   0   0   0   0   0
31    0   0   0   0   0   0   0   0   0   0   0   0   0   0
32    0   0   0   0   0   0   0   0   0   0   0   0   0   0
33    0   0   0   0   0   0   0   0   0   0   0   0   0   0
34    0   0   0   0   0   0   0   0   0   0   0   0   0   0
35    0   0   0   0   0   0   0   0   0   0   0   0   0   0
36    0   0   0   0   0   0   0   0   0   0   0   0   0   0
37    0   0   0   0   0   0   0   0   0   0   1   0   0   0
38    0   0   0   0   0   0   0   0   0   0   0   0   0   0
39    0   0   0   0   0   0   0   0   0   0   0   0   0   0
40    0   0   0   0   0   0   0   0   0   0   0   0   0   0
41    0   0   0   0   0   0   0   0   0   0   0   0   0   0
42    0   0   0   0   0   0   0   0   0   0   0   0   0   0
43    0   0   0   0   0   0   0   0   0   0   0   0   0   0
44    0   0   0   0   0   0   0   0   0   0   0   0   0   0
45    0   0   0   0   0   0   0   0   0   0   0   0   0   0
46    0   0   0   0   0   0   0   0   0   0   0   0   0   0
47    0   0   0   0   0   0   0   0   0   0   0   0   0   0
48    0   0   0   0   0   0   0   0   0   0   0   0   0   0
49    0   0   0   0   0   0   0   0   0   0   0   0   0   1
50    0   0   0   0   0   0   0   0   0   0   0   0   0   0
51    0   0   0   0   0   0   0   0   0   0   0   0   0   0
52    0   0   0   0   0   0   0   0   0   0   0   0   0   0
53    0   0   0   0   0   0   0   0   0   0   0   0   0   0
54    0   0   0   0   0   0   0   0   0   0   0   0   0   0
55    0   0   0   0   0   0   0   0   0   0   0   0   0   0
56    0   0   0   0   0   0   0   0   0   0   0   0   0   0
57    0   0   0   0   0   0   0   0   0   0   0   0   0   0
58    0   0   0   0   0   0   0   0   0   0   0   0   0   0
59    0   0   0   0   0   0   0   0   0   0   0   0   0   0
60    0   0   0   0   0   0   0   0   0   0   0   0   0   0
61    0   0   0   0   0   0   0   0   0   0   0   0   0   0
62    0   0   0   0   0   0   0   0   0   0   0   0   0   0
63    0   0   0   0   0   0   0   0   0   0   0   0   0   0
64    0   0   0   0   0   0   0   0   0   0   0   0   0   0
65    0   0   0   0   0   0   0   0   0   0   0   0   0   0
66    0   0   0   0   0   0   0   0   0   0   0   0   0   0
67    0   0   0   0   0   0   0   0   0   0   0   0   0   0
68    0   0   0   0   0   0   0   0   0   0   0   0   0   0
69    0   0   0   0   0   0   0   0   0   0   0   0   0   0
70    0   0   0   0   0   0   0   0   0   0   0   0   0   0
71    0   0   0   0   0   0   0   0   0   0   0   0   0   0
72    0   0   0   0   0   0   0   0   0   0   0   0   0   0
73    0   0   0   0   0   0   0   0   0   0   0   0   0   0
74    0   0   0   0   0   0   0   0   0   0   0   0   0   0
75    0   0   0   0   0   0   0   0   0   0   0   0   0   1
76    0   0   0   0   0   0   0   0   0   0   0   0   0   0
77    0   0   0   0   0   0   0   0   0   0   0   0   0   0
78    0   0   0   0   0   0   0   0   0   0   0   0   0   0
79    0   0   0   0   0   0   0   0   0   0   0   0   0   0
80    0   0   0   0   0   0   0   0   0   0   0   0   0   0
81    0   0   0   0   0   0   0   0   0   0   0   0   0   0
82    0   0   0   0   0   0   0   0   0   0   0   0   1   0
83    0   0   0   0   0   0   0   0   0   0   0   0   0   0
84    0   0   0   0   0   0   0   0   0   0   0   0   0   0
85    0   0   0   0   0   0   0   0   0   1   0   0   0   0
86    0   0   0   0   0   0   0   0   0   0   0   0   0   0
87    0   0   0   0   0   0   0   0   0   0   0   0   0   1
88    0   0   0   0   0   0   0   0   0   0   0   0   0   0
89    0   0   0   0   0   1   0   0   0   0   0   0   0   0
90    0   0   0   0   0   0   0   0   0   0   0   0   0   0
91    0   0   0   0   0   0   0   0   0   0   0   0   0   0
92    0   0   0   0   0   0   0   0   0   0   0   0   1   0
93    0   0   0   0   0   0   0   0   0   0   0   0   0   0
94    0   0   0   0   0   0   0   0   0   0   0   0   0   0
95    0   0   0   0   0   0   0   0   0   0   0   0   0   0
96    0   0   0   0   0   0   1   0   0   0   0   0   0   0
97    0   0   0   0   0   0   0   0   0   0   0   0   0   0
98    0   0   0   0   0   0   0   0   0   0   0   0   0   0
99    0   0   0   0   0   0   0   0   0   0   0   0   0   0
100   0   0   0   0   0   0   0   0   0   0   0   0   0   0
101   0   0   0   0   0   0   0   0   0   0   0   0   0   0
102   0   0   0   0   0   0   0   0   0   0   0   0   0   0
103   0   0   0   0   0   0   0   0   0   0   0   0   0   0
104   0   0   0   0   0   0   0   0   0   0   0   0   0   0
105   0   0   0   0   0   0   0   0   0   0   0   0   0   0
106   0   0   0   0   0   0   0   0   0   0   0   0   0   0
107   0   0   0   0   0   0   0   0   0   0   0   0   0   0
108   0   0   0   0   0   0   0   0   0   0   0   0   0   0
109   0   0   0   0   0   0   0   0   0   0   0   0   0   0
110   0   0   0   0   0   0   0   0   0   0   0   0   0   0
111   0   0   0   0   0   0   0   0   0   0   0   0   0   0
112   0   0   0   0   0   0   0   0   0   0   0   0   0   0
113   0   0   0   0   0   0   0   0   0   0   0   0   0   0
114   0   0   0   0   0   0   0   0   0   0   0   0   0   0
115   0   0   0   0   0   0   0   0   0   0   0   0   0   0
116   0   0   0   0   0   0   0   0   0   0   0   0   0   0
117   0   0   0   0   0   0   0   0   0   0   0   0   0   0
118   0   0   0   0   0   0   0   0   0   0   0   0   0   0
119   0   0   0   0   0   0   0   0   0   0   0   0   0   0
120   0   0   0   0   0   0   0   0   0   0   0   0   0   0
121   0   0   0   0   0   0   0   0   0   0   0   0   0   0
122   0   0   0   0   0   0   0   0   0   0   0   0   0   0
123   0   0   0   0   0   0   0   0   0   0   0   0   0   0
124   0   0   0   0   0   0   0   0   0   0   0   0   0   0
125   0   0   0   0   0   0   0   0   0   0   0   0   0   0
126   0   0   0   0   0   0   0   0   0   0   0   0   0   0
127   0   0   0   0   0   0   0   0   0   0   0   0   0   0
128   0   0   0   0   0   0   0   0   0   0   0   0   0   0
129   0   0   0   0   0   0   0   0   0   0   0   0   0   0
130   0   0   0   0   0   0   0   0   0   0   0   0   0   0
131   0   0   0   0   0   0   0   0   0   0   0   0   0   0
132   0   0   0   0   0   0   0   0   0   0   0   0   0   0
133   0   0   0   0   0   0   0   0   0   0   0   0   0   0
134   0   0   0   0   0   0   0   0   0   0   0   0   0   0
135   0   0   0   0   0   0   0   0   0   0   0   0   0   0
136   0   0   0   0   0   0   0   0   0   0   0   0   0   0
137   0   0   0   0   0   0   0   0   0   0   0   0   0   0
138   1   0   0   0   0   0   0   0   0   0   0   0   0   0
139   0   0   0   0   0   0   0   0   0   0   1   0   0   0
140   0   0   0   0   0   0   0   0   0   0   0   0   0   0
141   0   0   0   0   0   0   0   0   0   0   0   0   0   0
142   0   0   0   0   0   0   0   0   0   0   0   0   0   0
143   0   0   0   0   0   0   0   0   0   0   0   0   0   0
144   0   0   0   0   0   0   0   0   0   0   1   0   0   0
145   1   0   0   0   0   0   0   0   0   0   0   0   0   0
146   0   0   0   0   0   0   0   0   0   0   0   0   0   0
147   0   0   0   0   0   0   0   0   0   0   0   0   0   0
148   0   0   0   0   0   0   0   0   0   0   0   0   0   0
149   0   0   0   0   0   0   0   0   0   0   0   0   0   0
150   0   0   0   0   0   0   0   0   0   0   0   0   0   0
151   0   0   0   0   0   0   0   0   0   0   0   0   0   0
152   0   0   0   0   0   0   0   0   0   0   0   0   0   0
153   0   0   0   0   0   0   0   0   0   0   0   0   0   0
154   0   0   0   0   0   0   0   0   0   0   0   0   0   0
155   0   0   0   0   0   0   0   0   0   0   0   0   0   0
156   0   0   0   0   0   0   0   0   0   0   0   0   0   0
157   0   0   0   0   0   0   0   0   0   0   0   0   0   0
158   0   0   0   0   0   0   0   0   0   0   0   0   0   0
159   0   0   0   0   0   0   0   0   0   0   0   0   0   0
160   0   0   0   0   0   0   0   0   0   0   0   0   1   0
161   0   0   0   0   0   0   0   0   0   0   0   0   1   0
162   0   0   0   0   0   0   0   0   0   0   0   0   0   1
163   0   0   0   0   0   0   0   0   0   0   0   0   1   0
164   0   0   0   0   0   0   0   0   0   0   1   0   0   0
165   1   0   0   0   0   0   0   0   0   0   0   0   0   0
166   0   0   0   0   0   0   0   0   0   0   0   0   0   0
167   0   0   0   0   0   0   0   0   0   0   0   0   1   0
168   0   0   0   0   0   1   0   0   0   0   0   0   0   0
169   0   0   0   0   0   0   0   1   0   0   0   0   0   0
170   0   0   0   0   0   0   0   0   0   0   0   0   0   0
171   0   0   0   0   0   0   0   0   0   0   0   0   0   0
172   0   0   0   0   0   0   0   0   0   0   0   0   0   1
173   0   0   0   0   0   0   0   0   0   0   0   0   1   0
174   0   0   0   0   0   0   0   0   0   0   0   0   0   0
175   0   0   0   0   0   0   0   0   0   0   1   0   0   0
176   0   0   0   0   0   0   0   0   0   0   0   0   1   0
177   0   0   0   0   0   0   0   0   0   0   1   0   0   0
178   0   0   0   0   0   0   0   0   0   0   1   0   0   0
179   0   0   0   0   0   0   0   0   0   0   0   0   1   0
180   0   0   0   0   0   0   0   0   0   0   0   0   0   1
181   0   0   0   0   0   0   0   0   0   0   0   0   0   0
182   0   0   0   0   0   0   0   0   0   0   0   0   0   1
183   0   0   0   0   0   0   0   0   0   0   0   0   0   0
184   0   0   0   0   0   0   0   0   0   0   0   0   0   0
185   0   0   0   0   0   0   0   0   0   0   0   0   0   0
186   0   0   0   0   0   0   0   0   0   0   0   0   0   0
187   0   0   0   0   0   0   0   0   0   0   0   0   1   0
188   0   0   0   0   0   0   0   0   0   0   0   0   0   0
189   0   0   0   0   0   0   0   0   0   0   0   0   0   0
190   0   0   0   0   0   0   0   0   0   0   0   0   0   0
191   0   0   0   0   0   0   0   0   0   0   0   0   1   0
192   0   0   0   0   0   0   0   0   0   0   0   0   0   0
193   0   0   0   0   0   0   0   0   0   0   0   0   0   0
194   0   0   0   0   0   0   0   0   0   0   0   0   0   1
195   0   0   0   0   0   0   0   0   0   0   0   0   0   0
196   0   0   0   0   0   0   0   0   0   0   0   0   0   0
197   0   0   0   0   0   0   0   0   0   0   0   0   0   0
198   0   0   0   0   0   0   0   0   0   0   0   0   0   0
199   0   0   0   0   0   0   0   0   0   0   0   1   0   0
200   0   0   0   0   0   0   0   0   0   0   0   0   0   0
201   0   0   0   0   0   0   0   0   0   0   0   0   1   0
202   0   0   0   0   0   0   1   0   0   0   0   0   0   0
203   0   0   0   0   0   0   0   0   0   0   0   0   0   0
204   0   0   0   0   0   0   0   0   0   0   0   0   1   0
205   0   0   0   0   0   0   0   0   0   0   0   0   0   0
206   0   0   0   0   0   0   0   0   0   0   0   0   0   0
207   0   0   0   0   0   0   0   0   0   0   0   0   0   0
208   0   0   0   0   0   0   0   0   0   0   0   0   0   0
209   0   0   0   0   0   0   1   0   0   0   0   0   0   0
210   0   0   0   0   0   0   0   0   0   0   0   0   0   0
211   0   0   0   0   0   0   0   0   0   0   0   1   0   0
212   0   0   0   0   0   0   0   0   0   0   0   0   1   0
213   0   0   0   0   0   0   0   0   0   0   0   0   0   0
214   0   0   0   0   0   0   0   0   0   0   0   0   0   0
215   0   0   0   0   0   0   0   0   0   0   0   0   0   0
216   0   0   0   0   0   0   0   0   0   0   0   0   0   0
217   0   0   0   0   0   0   0   0   0   0   1   0   0   0
218   0   0   0   0   0   0   0   0   0   0   0   0   1   0
219   0   0   0   0   0   0   0   0   0   0   0   0   0   0
220   0   0   0   0   0   0   0   0   0   0   0   0   0   0
221   0   0   0   0   0   0   0   0   0   0   0   0   0   0
222   0   0   0   0   0   0   0   0   0   1   0   0   0   0
223   0   0   0   0   0   0   0   0   0   0   0   0   0   0
224   0   0   0   0   0   0   0   0   0   1   0   0   0   0
225   0   0   0   0   0   0   0   0   0   0   1   0   0   0
226   0   0   0   0   0   0   0   0   0   0   0   0   0   0
227   0   0   0   0   0   0   0   0   0   1   0   0   0   0
228   0   0   0   0   0   0   0   0   0   0   0   0   1   0
229   0   0   0   0   0   0   0   0   0   0   0   0   1   0
230   0   0   0   0   0   0   0   0   0   0   0   0   0   0
231   0   0   0   0   0   0   0   0   0   0   0   0   1   0
232   0   0   0   0   0   0   0   0   0   0   0   0   0   0
233   0   0   0   0   0   0   0   0   0   0   1   0   0   0
234   0   0   0   0   0   0   0   0   0   0   0   0   0   0
235   0   0   0   0   0   0   0   0   0   0   0   0   0   0
236   0   0   0   0   0   0   0   0   0   0   0   0   0   0
237   1   0   0   0   0   0   0   0   0   0   0   0   0   0
238   0   0   0   0   1   0   0   0   0   0   0   0   0   0
239   0   0   0   0   0   0   0   0   0   0   0   0   0   0
240   0   0   0   0   0   0   0   0   0   0   0   0   0   0
241   0   0   0   0   0   0   0   0   0   0   0   0   0   0
242   0   0   0   0   0   0   0   0   0   0   0   0   0   0
243   1   0   0   0   0   0   0   0   0   0   0   0   0   0
244   1   0   0   0   0   0   0   0   0   0   0   0   0   0
245   0   0   0   0   0   0   0   0   0   0   0   0   0   0
246   0   0   0   0   0   0   0   0   0   0   0   0   0   0
247   0   0   0   0   0   0   0   0   0   0   0   0   0   0
248   0   0   0   0   0   0   0   0   0   0   0   0   0   0
249   0   0   0   0   0   0   0   0   0   0   0   0   0   0
250   0   0   0   0   0   0   0   0   0   0   0   0   0   0
251   0   0   0   0   0   0   0   0   0   0   0   0   0   0
252   0   0   0   0   0   0   0   0   0   0   0   0   0   0
253   0   0   0   0   0   0   0   0   0   0   0   0   0   0
254   0   0   0   0   0   0   0   0   0   0   0   0   0   0
255   0   0   0   0   0   0   0   0   0   0   0   0   0   0
256   0   0   0   0   0   0   0   0   0   0   0   0   1   0
257   0   0   0   0   0   0   0   0   0   0   0   0   0   1
258   0   0   0   0   0   0   0   0   0   0   0   0   0   0
259   0   0   0   0   0   0   0   0   0   0   0   0   0   0
260   0   0   0   0   0   0   0   0   0   0   0   0   0   0
261   0   0   0   0   0   0   0   0   0   0   1   0   0   0
262   0   0   0   0   0   0   0   0   0   0   0   0   0   0
263   0   0   0   0   0   0   0   0   0   0   0   0   1   0
264   0   0   0   0   0   0   0   0   0   0   0   0   0   0
265   0   0   0   0   0   0   0   0   0   0   0   0   0   0
266   0   0   0   0   0   0   0   0   0   0   0   0   0   0
267   0   0   0   0   0   0   0   0   0   0   0   0   0   0
268   0   0   0   0   0   0   0   1   0   0   0   0   0   0
269   0   0   0   0   0   1   0   0   0   0   0   0   0   0
270   0   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   0   0   0   0   0   0   0   0   0   0   0
272   0   0   0   0   0   0   0   0   0   0   0   0   0   0
273   0   0   0   0   0   0   0   0   0   0   0   0   0   0
274   0   0   0   0   0   0   0   0   1   0   0   0   0   0
275   0   0   0   0   0   0   0   0   0   0   0   0   0   0
276   0   0   0   0   0   0   0   0   0   0   0   0   0   0
277   0   0   0   0   0   0   0   0   0   0   0   0   0   0
278   0   0   0   0   0   0   0   0   0   0   0   0   1   0
279   0   0   0   0   0   0   0   0   1   0   0   0   0   0
280   0   0   0   0   0   0   0   0   0   0   0   0   0   0
281   0   0   0   0   0   0   0   0   0   0   0   0   0   0
282   0   0   0   0   0   0   0   0   0   0   0   0   0   0
283   0   0   0   0   0   0   0   0   0   0   0   0   0   0
284   0   0   0   0   0   0   0   0   0   0   0   0   0   0
285   0   0   0   0   0   0   0   0   0   0   0   0   0   0
286   0   0   0   0   0   0   0   0   0   0   0   0   0   0
287   0   0   0   0   0   0   1   0   0   0   0   0   0   0
288   0   0   0   0   0   0   0   0   0   0   0   0   1   0
289   0   0   0   0   0   0   0   0   0   0   0   0   0   0
290   0   0   0   0   0   0   0   0   0   0   0   0   0   0
291   0   0   0   0   0   0   0   0   0   0   0   0   0   0
292   0   0   0   0   0   0   0   0   0   0   0   0   0   0
293   0   0   0   0   0   0   0   0   0   0   0   0   0   0
294   0   0   0   0   0   0   0   0   0   0   0   0   0   0
295   1   0   0   0   0   0   0   0   0   0   0   0   0   0
296   0   0   0   0   0   0   1   0   0   0   0   0   0   0
297   0   0   0   0   0   0   0   0   0   0   0   0   0   0
298   0   0   0   0   0   0   0   0   0   0   0   0   0   0
299   1   0   0   0   0   0   0   0   0   0   0   0   0   0
300   0   0   0   0   0   0   0   0   0   0   0   0   0   0
301   0   0   0   0   0   0   0   0   0   0   0   0   0   0
302   0   0   0   0   0   0   0   0   0   0   0   0   0   0
303   0   0   0   0   0   0   0   0   0   0   0   0   0   0
304   0   0   0   0   0   0   0   0   0   0   0   0   0   0
305   0   0   0   0   0   0   0   0   0   0   0   0   0   0
306   0   0   0   0   0   0   0   0   0   0   0   0   0   0
307   0   0   0   0   0   0   0   0   0   0   0   0   0   0
308   0   0   0   0   0   0   0   0   0   0   0   0   0   0
309   0   0   0   0   0   0   0   0   0   0   0   0   0   0
310   0   0   0   0   0   0   0   0   0   1   0   0   0   0
311   0   0   0   0   0   0   0   0   0   0   0   0   0   0
312   0   0   0   0   0   0   0   0   0   0   0   0   0   0
313   0   0   0   0   0   0   0   0   0   0   0   0   0   0
314   1   0   0   0   0   0   0   0   0   0   0   0   0   0
315   0   0   0   0   0   0   1   0   0   0   0   0   0   0
316   0   0   0   0   0   0   0   0   0   0   0   0   0   0
317   0   0   0   0   0   0   0   0   0   0   1   0   0   0
318   0   0   0   0   0   0   0   0   0   0   0   0   0   0
319   0   0   0   0   0   1   0   0   0   0   0   0   0   0
320   0   0   0   0   0   0   0   0   0   0   0   0   0   0
321   0   0   0   0   0   0   0   0   0   0   0   0   0   0
322   1   0   0   0   0   0   0   0   0   0   0   0   0   0
323   0   0   0   0   0   0   0   0   0   0   1   0   0   0
324   0   0   0   0   0   0   0   0   0   0   0   0   0   0
325   0   0   0   0   0   0   0   0   0   0   0   0   0   0
326   0   0   0   0   0   0   0   0   0   0   0   0   0   0
327   0   0   0   0   0   0   0   0   0   0   1   0   0   0
328   0   0   0   0   0   0   0   0   0   0   0   0   0   0
329   0   0   0   0   0   0   0   0   0   0   0   0   0   0
330   0   0   0   0   0   0   0   0   0   0   0   0   1   0
331   0   0   0   0   0   0   0   0   0   0   0   1   0   0

In [123]:
#group the reason into 4 columns base on our defined class
#axis = 1 indidcate find max for each row
# loc use the labal(columns name)
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [124]:
#check
reason_type_1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: int64

In [125]:
df.head()

,reason_for_absence,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [126]:
#drop reason_for_absense
df = df.drop(['reason_for_absence'], axis=1)
df.head()

,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [127]:
#concatenate the 4 reson into our main df
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis =1)
df.head()

,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [132]:
#rename the 4 reason group of absense
#numerical columns name so no ' '
df.rename(columns={
    0: 'reason_1',
    1: 'reason_2',
    2: 'reason_3',
    3: 'reason_4'}, inplace=True)

In [133]:
df.head()

,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,reason_1,reason_2,reason_3,reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [134]:
#re-order the column
df.columns.values

array(['date', 'transportation_expense', 'distance_to_work', 'age',
       'daily_work_load_average', 'body_mass_index', 'education',
       'children', 'pets', 'absenteeism_time_in_hours', 'reason_1',
       'reason_2', 'reason_3', 'reason_4'], dtype=object)

In [135]:
reorder_columns = ['reason_1', 'reason_2', 'reason_3', 'reason_4', 
                   'date', 'transportation_expense', 'distance_to_work', 'age',
                   'daily_work_load_average', 'body_mass_index', 'education',
                   'children', 'pets', 'absenteeism_time_in_hours']

df = df[reorder_columns]

df.head()

,reason_1,reason_2,reason_3,reason_4,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [147]:
#create a checkpoint
df_reason_mod = df.copy()

In [148]:
df_reason_mod

,reason_1,reason_2,reason_3,reason_4,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,0,0,0,1,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,0,0,0,1,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,0,0,0,1,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,0,0,1,0,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,0,0,0,1,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,1,0,0,0,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,1,0,0,0,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,1,0,0,0,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,1,0,0,0,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,1,0,0,0,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,0,0,0,1,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,0,0,1,0,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,1,0,0,0,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,0,0,0,1,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,1,0,0,0,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,1,0,0,0,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,1,0,0,0,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,0,0,0,1,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,0,0,1,0,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,0,0,0,1,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,0,0,0,1,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,0,0,0,1,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,0,0,1,0,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,0,0,0,1,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,0,0,1,0,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,0,0,1,0,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,0,0,0,1,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,0,0,1,0,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,0,0,0,1,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,0,0,0,1,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,0,0,0,1,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,1,0,0,0,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,0,0,0,1,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,0,0,0,1,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,0,0,0,1,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,0,0,0,1,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,0,0,0,1,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,0,0,1,0,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,0,0,0,1,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,0,0,0,1,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,0,0,0,1,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,0,0,0,1,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,0,0,0,1,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,1,0,0,0,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,0,0,0,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,0,0,0,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,0,0,0,1,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,0,0,0,1,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,0,0,0,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,0,0,0,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,0,0,1,0,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,0,0,0,1,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,0,0,0,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,0,0,0,1,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,0,0,0,1,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,0,0,0,1,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,0,0,0,1,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,0,0,0,1,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,0,0,0,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,0,0,0,1,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,0,0,0,1,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,0,0,0,1,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,0,0,0,1,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,0,0,0,1,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,0,0,0,1,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,0,0,0,1,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,0,0,0,1,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,0,0,0,1,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,0,0,1,0,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,1,0,0,0,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,0,0,0,1,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,0,0,0,1,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,0,0,0,1,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,0,0,0,1,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,0,0,0,1,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,0,0,0,1,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,1,0,0,0,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,0,0,1,0,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,0,0,0,1,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,1,0,0,0,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,0,0,0,1,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,1,0,0,0,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,0,0,0,1,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,1,0,0,0,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,0,0,0,1,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,0,0,1,0,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,1,0,0,0,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,0,0,0,1,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,0,0,0,1,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,0,0,0,1,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,1,0,0,0,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,0,0,0,1,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,0,0,0,1,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,0,0,1,0,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,0,0,0,1,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,0,0,0,1,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,0,0,0,1,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,0,0,0,1,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,0,0,1,0,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,0,0,0,1,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,0,0,0,1,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,0,0,0,1,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,0,0,0,1,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,0,0,0,1,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,0,0,0,1,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,0,0,1,0,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,0,0,0,1,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,0,0,0,1,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,0,0,1,0,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,0,0,0,1,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,0,0,1,0,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,0,0,0,1,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,0,0,0,1,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,0,0,0,1,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,0,0,0,1,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,0,0,0,1,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,0,0,0,1,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,0,0,0,1,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,0,0,0,1,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,0,0,0,1,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,0,0,0,1,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,0,0,0,1,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,0,0,0,1,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,0,0,1,0,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,0,0,1,0,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,0,0,0,1,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,0,0,0,1,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,0,0,0,1,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,0,0,0,1,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,0,0,0,1,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,0,0,0,1,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,0,0,0,1,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,1,0,0,0,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,1,0,0,0,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,0,0,0,1,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,0,0,0,1,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,0,0,0,1,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,0,0,0,1,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,1,0,0,0,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,1,0,0,0,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,0,0,0,1,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,0,0,0,1,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,0,0,0,1,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,0,0,0,1,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,0,0,0,1,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,0,0,1,0,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,0,0,0,1,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,0,0,0,1,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,0,0,1,0,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,0,0,0,1,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,0,0,1,0,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,0,0,1,0,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,0,1,0,0,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,0,0,0,1,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,1,0,0,0,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,1,0,0,0,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,1,0,0,0,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,1,0,0,0,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,1,0,0,0,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,1,0,0,0,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,0,0,0,1,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,1,0,0,0,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,1,0,0,0,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,1,0,0,0,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,0,0,0,1,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,0,0,0,1,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,1,0,0,0,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,1,0,0,0,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,0,0,0,1,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,1,0,0,0,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,1,0,0,0,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,1,0,0,0,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,1,0,0,0,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,1,0,0,0,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,1,0,0,0,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,0,0,0,1,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,1,0,0,0,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,0,0,0,1,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,0,0,0,1,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,0,0,0,1,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,0,0,0,1,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,1,0,0,0,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,0,0,0,1,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,0,0,0,1,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,0,0,0,1,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,1,0,0,0,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,0,0,0,1,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,0,0,0,1,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,1,0,0,0,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,0,0,0,1,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,0,0,0,1,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,0,0,1,0,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,0,0,1,0,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,1,0,0,0,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,0,0,1,0,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,1,0,0,0,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,0,0,0,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,0,0,0,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,1,0,0,0,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,0,0,0,1,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,0,0,0,1,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,0,0,1,0,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,0,0,1,0,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,1,0,0,0,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,0,0,0,1,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,1,0,0,0,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,1,0,0,0,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,0,0,0,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,0,0,0,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,0,0,0,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,0,0,0,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,1,0,0,0,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,1,0,0,0,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,0,0,0,1,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,0,0,1,0,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,0,0,0,1,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,1,0,0,0,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,0,0,0,1,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,1,0,0,0,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,1,0,0,0,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,0,0,0,1,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,1,0,0,0,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,1,0,0,0,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,0,0,0,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,0,0,0,1,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,1,0,0,0,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,0,0,0,1,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,1,0,0,0,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,0,0,0,1,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,0,0,0,1,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,0,0,1,0,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,1,0,0,0,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,1,0,0,0,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,0,0,0,1,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,0,0,0,1,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,0,0,1,0,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,0,0,0,1,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,1,0,0,0,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,1,0,0,0,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,0,0,0,1,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,0,0,0,1,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,0,0,0,1,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,0,0,0,1,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,0,0,1,0,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,0,0,1,0,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,0,0,0,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,0,0,1,0,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,0,0,1,0,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,0,0,0,1,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,0,0,1,0,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,1,0,0,0,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,1,0,0,0,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,0,0,0,1,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,0,0,0,1,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,0,0,0,1,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,1,0,0,0,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,0,0,0,1,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,1,0,0,0,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,0,0,0,1,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,0,0,0,1,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,0,0,0,1,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,0,0,1,0,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,1,0,0,0,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,1,0,0,0,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,1,0,0,0,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,0,0,0,1,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,0,0,1,0,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,0,0,0,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,1,0,0,0,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,0,0,0,1,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,0,0,0,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,0,0,0,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,1,0,0,0,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,1,0,0,0,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,0,0,0,1,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,0,0,0,1,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,0,0,0,1,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,0,0,0,1,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,0,0,0,1,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,0,0,0,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,0,0,0,1,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,1,0,0,0,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,1,0,0,0,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,0,0,0,1,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,0,0,0,1,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,0,0,0,1,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,0,0,0,1,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,0,0,0,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,0,0,0,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,1,0,0,0,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,1,0,0,0,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,0,0,0,1,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,0,0,0,1,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,1,0,0,0,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,0,0,0,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,0,0,1,0,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,0,0,0,1,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,0,0,0,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,0,0,0,1,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,0,0,0,1,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,0,0,0,1,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,0,0,0,1,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,0,0,0,1,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,0,0,0,1,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,1,0,0,0,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,0,0,0,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,0,0,0,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,0,0,0,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,1,0,0,0,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,1,0,0,0,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,0,0,0,1,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,1,0,0,0,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,0,0,0,1,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,1,0,0,0,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,0,0,0,1,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,0,0,0,1,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,1,0,0,0,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,1,0,0,0,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,0,0,0,1,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,0,0,0,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,0,0,1,0,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,1,0,0,0,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,0,0,0,1,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,0,0,0,1,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,1,0,0,0,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,1,0,0,0,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,1,0,0,0,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,0,0,0,1,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,1,0,0,0,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,0,1,0,0,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,0,0,0,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,0,0,0,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,0,0,0,1,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,1,0,0,0,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,0,0,0,1,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,0,0,0,1,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,0,0,0,1,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,0,0,0,1,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,0,0,0,1,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,1,0,0,0,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,0,0,0,1,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,0,0,0,1,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,0,0,0,1,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,0,0,0,1,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,0,0,0,1,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,0,0,0,1,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,1,0,0,0,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,0,0,0,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,0,0,0,1,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,0,0,0,1,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,0,0,0,1,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,0,0,1,0,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,0,0,0,1,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,0,0,1,0,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,0,0,0,1,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,0,0,0,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,0,0,0,1,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,0,0,0,1,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,1,0,0,0,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,0,0,0,1,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,0,0,0,1,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,0,0,0,1,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,0,0,0,1,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,0,0,0,1,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,0,0,0,1,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,1,0,0,0,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,0,0,0,1,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,0,0,0,1,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,0,0,0,1,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,0,0,0,1,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,0,0,0,1,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,1,0,0,0,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,0,0,0,1,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,0,0,0,1,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,0,0,0,1,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,0,0,0,1,13/02/2017,179,51,38,251.818,31,1,0,0,3

In [149]:
#date column
type(df_reason_mod['date'][0])

str

In [150]:
df_reason_mod['date'] = pd.to_datetime(df_reason_mod['date'], format='%d/%m/%Y')

In [153]:
type(df_reason_mod['date'][1])

pandas._libs.tslibs.timestamps.Timestamp

In [154]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   reason_1                   700 non-null    int64
 1   reason_2                   700 non-null    int64
 2   reason_3                   700 non-null    int64
 3   reason_4                   700 non-null    int64
 4   date                       700 non-null    datetime64[ns]
 5   transportation_expense     700 non-null    int64
 6   distance_to_work           700 non-null    int64
 7   age                        700 non-null    int64
 8   daily_work_load_average    700 non-null    float64
 9   body_mass_index            700 non-null    int64
 10  education                  700 non-null    int64
 11  children                   700 non-null    int64
 12  pets                       700 non-null    int64
 13  absenteeism_time_in_hours  700 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(12)
memory usage: 76.7 KB

In [155]:
df_reason_mod

,reason_1,reason_2,reason_3,reason_4,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,1,0,0,2
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,1,1,4,8
7,0,0,0,1,2015-07-24,260,50,36,239.554,23,1,4,0,4
8,0,0,1,0,2015-07-06,155,12,34,239.554,25,1,2,0,40
9,0,0,0,1,2015-07-13,235,11,37,239.554,29,3,1,1,8
10,1,0,0,0,2015-07-20,260,50,36,239.554,23,1,4,0,8
11,1,0,0,0,2015-07-14,260,50,36,239.554,23,1,4,0,8
12,1,0,0,0,2015-07-15,260,50,36,239.554,23,1,4,0,8
13,1,0,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,1
14,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,4
15,1,0,0,0,2015-07-17,246,25,41,239.554,23,1,0,0,8
16,0,0,0,1,2015-07-17,179,51,38,239.554,31,1,0,0,2
17,0,0,1,0,2015-07-27,179,51,38,239.554,31,1,0,0,8
18,1,0,0,0,2015-07-30,189,29,33,239.554,25,1,2,2,8
19,0,0,0,1,2015-08-05,248,25,47,205.917,32,1,2,1,2
20,1,0,0,0,2015-08-12,330,16,28,205.917,25,2,0,0,8
21,1,0,0,0,2015-08-03,179,51,38,205.917,31,1,0,0,1
22,1,0,0,0,2015-08-10,361,52,28,205.917,27,1,1,4,40
23,0,0,0,1,2015-08-14,260,50,36,205.917,23,1,4,0,4
24,0,0,1,0,2015-08-17,289,36,33,205.917,30,1,2,1,8
25,0,0,0,1,2015-08-24,361,52,28,205.917,27,1,1,4,7
26,0,0,0,1,2015-08-04,289,36,33,205.917,30,1,2,1,1
27,0,0,0,1,2015-08-12,157,27,29,205.917,22,1,0,0,4
28,0,0,1,0,2015-08-19,289,36,33,205.917,30,1,2,1,8
29,0,0,0,1,2015-08-28,179,51,38,205.917,31,1,0,0,2
30,0,0,1,0,2015-08-17,179,51,38,205.917,31,1,0,0,8
31,0,0,1,0,2015-08-27,235,29,48,205.917,33,1,1,5,8
32,0,0,0,1,2015-08-27,235,11,37,205.917,29,3,1,1,4
33,0,0,1,0,2015-08-17,235,29,48,205.917,33,1,1,5,8
34,0,0,0,1,2015-08-17,179,51,38,205.917,31,1,0,0,2
35,0,0,0,1,2015-08-17,361,52,28,205.917,27,1,1,4,1
36,0,0,0,1,2015-08-04,289,36,33,205.917,30,1,2,1,8
37,1,0,0,0,2015-08-20,291,50,32,205.917,23,1,0,0,4
38,0,0,0,1,2015-08-21,235,29,48,205.917,33,1,1,5,8
39,0,0,0,1,2015-08-28,260,50,36,205.917,23,1,4,0,4
40,0,0,0,1,2015-09-01,184,42,27,241.476,21,1,0,0,2
41,0,0,0,1,2015-09-07,118,10,37,241.476,28,1,0,0,4
42,0,0,0,1,2015-09-01,179,51,38,241.476,31,1,0,0,4
43,0,0,1,0,2015-09-08,235,20,43,241.476,38,1,1,0,8
44,0,0,0,1,2015-09-09,155,12,34,241.476,25,1,2,0,2
45,0,0,0,1,2015-09-13,118,10,37,241.476,28,1,0,0,3
46,0,0,0,1,2015-09-14,179,51,38,241.476,31,1,0,0,3
47,0,0,0,1,2015-09-24,291,31,40,241.476,25,1,1,1,4
48,0,0,0,1,2015-09-04,260,50,36,241.476,23,1,4,0,8
49,1,0,0,0,2015-09-14,291,31,40,241.476,25,1,1,1,32
50,0,0,0,0,2015-09-21,260,50,36,241.476,23,1,4,0,0
51,0,0,0,0,2015-09-28,225,26,28,241.476,24,1,1,2,0
52,0,0,0,1,2015-09-08,225,26,28,241.476,24,1,1,2,2
53,0,0,0,1,2015-09-15,118,10,37,241.476,28,1,0,0,2
54,0,0,0,0,2015-09-22,289,36,33,241.476,30,1,2,1,0
55,0,0,0,0,2015-09-29,118,13,50,241.476,31,1,1,0,0
56,0,0,1,0,2015-09-16,225,26,28,241.476,24,1,1,2,3
57,0,0,0,1,2015-09-23,179,51,38,241.476,31,1,0,0,3
58,0,0,0,0,2015-09-30,369,17,31,241.476,25,1,3,0,0
59,0,0,0,1,2015-09-11,248,25,47,241.476,32,1,2,1,1
60,0,0,0,1,2015-09-18,179,51,38,241.476,31,1,0,0,3
61,0,0,0,1,2015-09-25,260,50,36,241.476,23,1,4,0,4
62,0,0,0,1,2015-10-06,179,51,38,253.465,31,1,0,0,3
63,0,0,0,1,2015-10-13,118,10,37,253.465,28,1,0,0,3
64,0,0,0,0,2015-10-14,118,13,50,253.465,31,1,1,0,0
65,0,0,0,1,2015-10-15,179,26,30,253.465,19,3,0,0,1
66,0,0,0,1,2015-10-16,179,51,38,253.465,31,1,0,0,3
67,0,0,0,1,2015-10-16,225,26,28,253.465,24,1,1,2,3
68,0,0,0,1,2015-10-06,118,10,37,253.465,28,1,0,0,3
69,0,0,0,1,2015-10-14,225,26,28,253.465,24,1,1,2,2
70,0,0,0,1,2015-10-21,248,25,47,253.465,32,1,2,1,2
71,0,0,0,1,2015-10-22,291,31,40,253.465,25,1,1,1,5
72,0,0,0,1,2015-10-21,179,51,38,253.465,31,1,0,0,8
73,0,0,0,1,2015-10-21,225,26,28,253.465,24,1,1,2,3
74,0,0,1,0,2015-10-22,260,50,36,253.465,23,1,4,0,16
75,1,0,0,0,2015-10-13,291,31,40,253.465,25,1,1,1,8
76,0,0,0,1,2015-10-20,225,26,28,253.465,24,1,1,2,2
77,0,0,0,1,2015-10-21,289,36,33,253.465,30,1,2,1,8
78,0,0,0,1,2015-10-23,361,52,28,253.465,27,1,1,4,1
79,0,0,0,1,2015-10-30,260,50,36,253.465,23,1,4,0,3
80,0,0,0,1,2015-11-05,179,51,38,306.345,31,1,0,0,1
81,0,0,0,1,2015-11-04,225,26,28,306.345,24,1,1,2,1
82,1,0,0,0,2015-11-05,179,51,38,306.345,31,1,0,0,8
83,0,0,1,0,2015-11-12,179,22,40,306.345,22,2,2,0,8
84,0,0,0,1,2015-11-19,291,31,40,306.345,25,1,1,1,5
85,1,0,0,0,2015-11-02,155,12,34,306.345,25,1,2,0,32
86,0,0,0,1,2015-11-09,189,29,33,306.345,25,1,2,2,8
87,1,0,0,0,2015-11-16,291,31,40,306.345,25,1,1,1,40
88,0,0,0,1,2015-11-18,225,26,28,306.345,24,1,1,2,1
89,1,0,0,0,2015-11-20,155,12,34,306.345,25,1,2,0,8
90,0,0,0,1,2015-11-18,225,26,28,306.345,24,1,1,2,3
91,0,0,1,0,2015-11-25,179,22,40,306.345,22,2,2,0,8
92,1,0,0,0,2015-11-20,225,26,28,306.345,24,1,1,2,3
93,0,0,0,1,2015-11-27,260,50,36,306.345,23,1,4,0,4
94,0,0,0,1,2015-11-02,248,25,47,306.345,32,1,2,1,1
95,0,0,0,1,2015-11-10,225,26,28,306.345,24,1,1,2,3
96,1,0,0,0,2015-11-11,289,36,33,306.345,30,1,2,1,24
97,0,0,0,1,2015-11-26,291,31,40,306.345,25,1,1,1,3
98,0,0,0,1,2015-12-01,248,25,47,261.306,32,1,2,1,1
99,0,0,1,0,2015-12-01,118,10,37,261.306,28,1,0,0,64
100,0,0,0,1,2015-12-02,118,13,50,261.306,31,1,1,0,2
101,0,0,0,1,2015-12-02,235,11,37,261.306,29,3,1,1,8
102,0,0,0,1,2015-12-03,225,26,28,261.306,24,1,1,2,2
103,0,0,0,1,2015-12-04,260,50,36,261.306,23,1,4,0,8
104,0,0,1,0,2015-12-08,118,10,37,261.306,28,1,0,0,56
105,0,0,0,1,2015-12-09,361,52,28,261.306,27,1,1,4,8
106,0,0,0,1,2015-12-10,225,26,28,261.306,24,1,1,2,3
107,0,0,0,1,2015-12-11,260,50,36,261.306,23,1,4,0,3
108,0,0,0,1,2015-12-15,225,26,28,261.306,24,1,1,2,2
109,0,0,0,1,2015-12-16,361,52,28,261.306,27,1,1,4,8
110,0,0,0,1,2015-12-11,118,10,37,261.306,28,1,0,0,2
111,0,0,1,0,2015-12-18,246,25,41,261.306,23,1,0,0,8
112,0,0,0,1,2015-12-18,225,26,28,261.306,24,1,1,2,2
113,0,0,0,1,2016-01-06,225,26,28,308.593,24,1,1,2,1
114,0,0,1,0,2016-01-04,118,10,37,308.593,28,1,0,0,1
115,0,0,0,1,2016-01-05,118,10,37,308.593,28,1,0,0,1
116,0,0,1,0,2016-01-05,155,12,34,308.593,25,1,2,0,8
117,0,0,0,1,2016-01-06,225,26,28,308.593,24,1,1,2,2
118,0,0,0,1,2016-01-07,184,42,27,308.593,21,1,0,0,2
119,0,0,0,1,2016-01-07,225,26,28,308.593,24,1,1,2,2
120,0,0,0,1,2016-01-08,225,26,28,308.593,24,1,1,2,1
121,0,0,0,1,2016-01-11,118,10,37,308.593,28,1,0,0,2
122,0,0,0,1,2016-01-12,225,26,28,308.593,24,1,1,2,2
123,0,0,0,1,2016-01-12,118,10,37,308.593,28,1,0,0,2
124,0,0,0,1,2016-01-13,118,10,37,308.593,28,1,0,0,2
125,0,0,0,1,2016-01-14,118,10,37,308.593,28,1,0,0,2
126,0,0,0,1,2016-01-15,118,10,37,308.593,28,1,0,0,2
127,0,0,0,1,2016-01-11,118,10,37,308.593,28,1,0,0,2
128,0,0,0,1,2016-01-12,118,10,37,308.593,28,1,0,0,2
129,0,0,1,0,2016-01-12,179,26,30,308.593,19,3,0,0,8
130,0,0,1,0,2016-01-12,289,36,33,308.593,30,1,2,1,8
131,0,0,0,1,2016-01-13,118,10,37,308.593,28,1,0,0,2
132,0,0,0,1,2016-01-21,184,42,27,308.593,21,1,0,0,2
133,0,0,0,1,2016-01-28,118,10,37,308.593,28,1,0,0,2
134,0,0,0,1,2016-01-25,118,10,37,308.593,28,1,0,0,0
135,0,0,0,1,2016-01-26,225,26,28,308.593,24,1,1,2,1
136,0,0,0,1,2016-01-28,289,36,33,308.593,30,1,2,1,3
137,0,0,0,1,2016-02-05,184,42,27,302.585,21,1,0,0,1
138,1,0,0,0,2016-02-03,246,25,41,302.585,23,1,0,0,8
139,1,0,0,0,2016-02-10,179,51,38,302.585,31,1,0,0,8
140,0,0,0,1,2016-02-11,155,12,34,302.585,25,1,2,0,2
141,0,0,0,1,2016-02-11,189,29,33,302.585,25,1,2,2,8
142,0,0,0,1,2016-02-12,260,50,36,302.585,23,1,4,0,2
143,0,0,0,1,2016-02-12,289,36,33,302.585,30,1,2,1,8
144,1,0,0,0,2016-02-08,388,15,50,302.585,24,1,0,0,8
145,1,0,0,0,2016-02-09,388,15,50,302.585,24,1,0,0,8
146,0,0,0,1,2016-02-15,225,26,28,302.585,24,1,1,2,2
147,0,0,0,1,2016-02-09,225,26,28,302.585,24,1,1,2,2
148,0,0,0,1,2016-02-16,179,26,30,302.585,19,3,0,0,1
149,0,0,0,1,2016-02-23,184,42,27,302.585,21,1,0,0,8
150,0,0,0,1,2016-02-25,225,26,28,302.585,24,1,1,2,3
151,0,0,1,0,2016-02-15,330,16,28,302.585,25,2,0,0,8
152,0,0,0,1,2016-02-16,330,16,28,302.585,25,2,0,0,1
153,0,0,0,1,2016-02-17,225,26,28,302.585,24,1,1,2,1
154,0,0,1,0,2016-02-25,189,29,33,302.585,25,1,2,2,8
155,0,0,0,1,2016-03-01,291,50,32,343.253,23,1,0,0,2
156,0,0,1,0,2016-03-01,260,50,36,343.253,23,1,4,0,8
157,0,0,1,0,2016-03-08,157,27,29,343.253,22,1,0,0,3
158,0,1,0,0,2016-03-15,179,22,40,343.253,22,2,2,0,8
159,0,0,0,1,2016-03-16,291,31,40,343.253,25,1,1,1,8
160,1,0,0,0,2016-03-02,260,50,36,343.253,23,1,4,0,8
161,1,0,0,0,2016-03-03,179,26,30,343.253,19,3,0,0,8
162,1,0,0,0,2016-03-04,248,25,47,343.253,32,1,2,1,3
163,1,0,0,0,2016-03-04,260,50,36,343.253,23,1,4,0,40
164,1,0,0,0,2016-03-07,179,22,40,343.253,22,2,2,0,40
165,1,0,0,0,2016-03-14,155,12,34,343.253,25,1,2,0,16
166,0,0,0,1,2016-03-21,260,50,36,343.253,23,1,4,0,16
167,1,0,0,0,2016-03-22,155,12,34,343.253,25,1,2,0,8
168,1,0,0,0,2016-03-24,289,36,33,343.253,30,1,2,1,8
169,1,0,0,0,2016-03-24,179,22,40,343.253,22,2,2,0,8
170,0,0,0,1,2016-03-25,260,50,36,343.253,23,1,4,0,4
171,0,0,0,1,2016-03-25,225,26,28,343.253,24,1,1,2,1
172,1,0,0,0,2016-03-28,279,5,39,343.253,24,1,2,0,8
173,1,0,0,0,2016-03-29,179,51,38,343.253,31,1,0,0,24
174,0,0,0,1,2016-03-30,225,26,28,343.253,24,1,1,2,2
175,1,0,0,0,2016-03-28,225,26,28,343.253,24,1,1,2,8
176,1,0,0,0,2016-03-28,179,26,30,343.253,19,3,0,0,1
177,1,0,0,0,2016-03-29,225,26,28,343.253,24,1,1,2,8
178,1,0,0,0,2016-03-30,225,26,28,343.253,24,1,1,2,16
179,1,0,0,0,2016-03-30,179,51,38,343.253,31,1,0,0,3
180,1,0,0,0,2016-03-17,279,5,39,343.253,24,1,2,0,16
181,0,0,0,1,2016-03-18,225,26,28,343.253,24,1,1,2,2
182,1,0,0,0,2016-03-25,248,25,47,343.253,32,1,2,1,3
183,0,0,0,1,2016-03-28,225,26,28,343.253,24,1,1,2,1
184,0,0,0,1,2016-04-06,291,31,40,326.452,25,1,1,1,1
185,0,0,0,1,2016-04-13,225,26,28,326.452,24,1,1,2,1
186,0,0,0,1,2016-04-12,155,12,34,326.452,25,1,2,0,1
187,1,0,0,0,2016-04-13,246,25,41,326.452,23,1,0,0,24
188,0,0,0,1,2016-04-14,155,12,34,326.452,25,1,2,0,1
189,0,0,0,1,2016-04-15,225,26,28,326.452,24,1,1,2,2
190,0,0,0,1,2016-04-15,260,50,36,326.452,23,1,4,0,4
191,1,0,0,0,2016-04-06,179,51,38,326.452,31,1,0,0,24
192,0,0,0,1,2016-04-07,118,13,50,326.452,31,1,1,0,1
193,0,0,0,1,2016-04-08,291,31,40,326.452,25,1,1,1,3
194,1,0,0,0,2016-04-08,246,25,41,326.452,23,1,0,0,8
195,0,0,0,1,2016-04-22,291,31,40,326.452,25,1,1,1,1
196,0,0,0,1,2016-04-29,248,25,47,326.452,32,1,2,1,8
197,0,0,1,0,2016-04-29,260,50,36,326.452,23,1,4,0,56
198,0,0,1,0,2016-04-26,289,36,33,326.452,30,1,2,1,8
199,1,0,0,0,2016-04-27,155,12,34,326.452,25,1,2,0,24
200,0,0,1,0,2016-04-27,378,49,36,326.452,21,1,2,4,8
201,1,0,0,0,2016-04-28,289,36,33,326.452,30,1,2,1,16
202,1,0,0,0,2016-04-08,235,11,37,326.452,29,3,1,1,3
203,0,0,0,0,2016-04-04,235,29,48,326.452,33,1,1,5,0
204,1,0,0,0,2016-05-04,289,36,33,378.884,30,1,2,1,8
205,0,0,0,1,2016-05-05,155,12,34,378.884,25,1,2,0,2
206,0,0,0,1,2016-05-02,155,12,34,378.884,25,1,2,0,1
207,0,0,1,0,2016-05-03,179,51,38,378.884,31,1,0,0,8
208,0,0,1,0,2016-05-03,225,26,28,378.884,24,1,1,2,8
209,1,0,0,0,2016-05-11,184,42,27,378.884,21,1,0,0,4
210,0,0,0,1,2016-05-09,155,12,34,378.884,25,1,2,0,2
211,1,0,0,0,2016-05-10,179,51,38,378.884,31,1,0,0,1
212,1,0,0,0,2016-05-04,289,36,33,378.884,30,1,2,1,24
213,0,0,0,0,2016-05-11,279,5,39,378.884,24,1,2,0,0
214,0,0,0,0,2016-05-18,330,16,28,378.884,25,2,0,0,0
215,0,0,0,0,2016-05-25,378,49,36,378.884,21,1,2,4,0
216,0,0,0,0,2016-05-25,388,15,50,378.884,24,1,0,0,0
217,1,0,0,0,2016-05-24,179,51,38,378.884,31,1,0,0,1
218,1,0,0,0,2016-05-11,118,13,50,378.884,31,1,1,0,24
219,0,0,0,1,2016-05-27,361,52,28,378.884,27,1,1,4,8
220,0,0,1,0,2016-06-06,246,25,41,377.550,23,1,0,0,8
221,0,0,0,1,2016-06-13,361,52,28,377.550,27,1,1,4,8
222,1,0,0,0,2016-06-14,246,25,41,377.550,23,1,0,0,24
223,0,0,0,1,2016-06-16,291,31,40,377.550,25,1,1,1,4
224,1,0,0,0,2016-06-17,246,25,41,377.550,23,1,0,0,8
225,1,0,0,0,2016-06-13,179,51,38,377.550,31,1,0,0,8
226,0,0,0,1,2016-06-20,155,12,34,377.550,25,1,2,0,4
227,1,0,0,0,2016-06-27,246,25,41,377.550,23,1,0,0,8
228,1,0,0,0,2016-06-29,118,13,50,377.550,31,1,1,0,8
229,1,0,0,0,2016-06-03,235,11,37,377.550,29,3,1,1,16
230,0,0,0,1,2016-06-07,118,13,50,377.550,31,1,1,0,1
231,1,0,0,0,2016-06-08,118,13,50,377.550,31,1,1,0,80
232,0,0,0,1,2016-06-09,378,49,36,377.550,21,1,2,4,8
233,1,0,0,0,2016-06-10,179,51,38,377.550,31,1,0,0,2
234,0,0,0,1,2016-06-20,289,48,49,377.550,36,1,0,2,2
235,0,0,0,1,2016-06-30,225,26,28,377.550,24,1,1,2,2
236,0,0,1,0,2016-07-05,155,12,34,275.312,25,1,2,0,16
237,1,0,0,0,2016-07-06,118,13,50,275.312,31,1,1,0,8
238,1,0,0,0,2016-07-08,118,10,37,275.312,28,1,0,0,8
239,0,0,0,1,2016-07-08,118,10,37,275.312,28,1,0,0,4
240,0,0,0,1,2016-07-12,330,16,28,275.312,25,2,0,0,8
241,0,0,1,0,2016-07-14,179,26,30,275.312,19,3,0,0,8
242,0,0,0,1,2016-07-15,155,12,34,275.312,25,1,2,0,2
243,1,0,0,0,2016-07-18,330,16,28,275.312,25,2,0,0,8
244,1,0,0,0,2016-07-19,330,16,28,275.312,25,2,0,0,8
245,0,0,0,1,2016-07-18,157,27,29,275.312,22,1,0,0,3
246,0,0,0,1,2016-07-19,361,52,28,275.312,27,1,1,4,8
247,0,0,0,1,2016-07-20,289,36,33,275.312,30,1,2,1,8
248,0,0,0,1,2016-07-21,179,51,38,275.312,31,1,0,0,8
249,0,0,1,0,2016-07-11,289,36,33,275.312,30,1,2,1,32
250,0,0,1,0,2016-07-14,289,36,33,275.312,30,1,2,1,8
251,0,0,0,0,2016-07-21,260,50,36,275.312,23,1,4,0,0
252,0,0,1,0,2016-08-04,289,36,33,265.615,30,1,2,1,8
253,0,0,1,0,2016-08-11,157,27,29,265.615,22,1,0,0,3
254,0,0,0,1,2016-08-07,289,36,33,265.615,30,1,2,1,1
255,0,0,1,0,2016-08-08,228,14,58,265.615,22,1,2,1,8
256,1,0,0,0,2016-08-10,300,26,43,265.615,25,1,2,1,1
257,1,0,0,0,2016-08-10,300,26,43,265.615,25,1,2,1,2
258,0,0,0,1,2016-08-11,260,50,36,265.615,23,1,4,0,4
259,0,0,0,1,2016-08-08,289,36,33,265.615,30,1,2,1,4
260,0,0,0,1,2016-08-09,248,25,47,265.615,32,1,2,1,1
261,1,0,0,0,2016-08-10,268,11,33,265.615,25,2,0,0,8
262,0,0,0,1,2016-08-10,179,26,30,265.615,19,3,0,0,1
263,1,0,0,0,2016-08-10,118,13,50,265.615,31,1,1,0,3
264,0,0,0,1,2016-08-14,248,25,47,265.615,32,1,2,1,2
265,0,0,0,1,2016-08-15,235,11,37,265.615,29,3,1,1,1
266,0,0,0,1,2016-08-17,118,13,50,265.615,31,1,1,0,1
267,0,0,1,0,2016-08-24,235,11,37,265.615,29,3,1,1,8
268,1,0,0,0,2016-08-08,361,52,28,265.615,27,1,1,4,8
269,1,0,0,0,2016-08-30,184,42,27,265.615,21,1,0,0,8
270,1,0,0,0,2016-09-05,179,51,38,294.217,31,1,0,0,8
271,0,0,0,1,2016-09-09,179,51,38,294.217,31,1,0,0,3
272,0,0,1,0,2016-09-07,289,36,33,294.217,30,1,2,1,24
273,0,0,0,0,2016-09-08,235,20,43,294.217,38,1,1,0,0
274,1,0,0,0,2016-09-12,246,25,41,294.217,23,1,0,0,16
275,0,0,0,1,2016-09-13,291,31,40,294.217,25,1,1,1,3
276,0,0,0,0,2016-09-13,231,35,39,294.217,35,1,2,2,0
277,0,0,0,0,2016-09-13,291,50,32,294.217,23,1,0,0,0
278,1,0,0,0,2016-09-14,179,51,38,294.217,31,1,0,0,8
279,1,0,0,0,2016-09-14,246,25,41,294.217,23,1,0,0,32
280,0,0,0,1,2016-09-15,179,51,38,294.217,31,1,0,0,1
281,0,0,0,1,2016-09-16,291,31,40,294.217,25,1,1,1,4
282,0,0,0,1,2016-09-16,260,50,36,294.217,23,1,4,0,4
283,0,0,0,1,2016-09-14,235,20,43,294.217,38,1,1,0,8
284,0,0,0,1,2016-09-15,118,13,50,294.217,31,1,1,0,1
285,0,0,0,0,2016-09-15,235,20,43,294.217,38,1,1,0,0
286,0,0,0,1,2016-09-16,291,31,40,294.217,25,1,1,1,3
287,1,0,0,0,2016-09-26,291,31,40,294.217,25,1,1,1,40
288,1,0,0,0,2016-09-26,179,51,38,294.217,31,1,0,0,8
289,0,0,0,1,2016-10-05,289,36,33,265.017,30,1,2,1,8
290,0,0,0,1,2016-10-05,235,11,37,265.017,29,3,1,1,4
291,0,0,0,1,2016-10-05,289,36,33,265.017,30,1,2,1,8
292,0,0,0,1,2016-10-06,289,36,33,265.017,30,1,2,1,8
293,0,0,0,0,2016-10-06,118,13,50,265.017,31,1,1,0,0
294,0,0,0,0,2016-10-06,248,25,47,265.017,32,1,2,1,0
295,1,0,0,0,2016-10-12,179,26,30,265.017,19,3,0,0,8
296,1,0,0,0,2016-10-12,118,10,37,265.017,28,1,0,0,3
297,0,0,0,1,2016-10-12,369,17,31,265.017,25,1,3,0,8
298,0,0,0,1,2016-10-14,179,51,38,265.017,31,1,0,0,1
299,1,0,0,0,2016-10-14,179,26,30,265.017,19,3,0,0,64
300,0,0,0,0,2016-10-14,235,20,43,265.017,38,1,1,0,0
301,0,0,1,0,2016-10-15,289,36,33,265.017,30,1,2,1,16
302,0,0,0,1,2016-10-16,260,50,36,265.017,23,1,4,0,3
303,0,0,0,0,2016-10-16,235,20,43,265.017,38,1,1,0,0
304,0,0,0,1,2016-10-19,235,20,43,265.017,38,1,1,0,2
305,0,0,0,1,2016-10-19,235,20,43,265.017,38,1,1,0,2
306,0,0,0,1,2016-10-20,118,13,50,265.017,31,1,1,0,1
307,0,0,0,1,2016-10-20,291,31,40,265.017,25,1,1,1,4
308,0,0,0,1,2016-10-22,179,26,30,265.017,19,3,0,0,16
309,0,0,0,1,2016-10-22,118,13,50,265.017,31,1,1,0,1
310,1,0,0,0,2016-10-26,361,52,28,265.017,27,1,1,4,8
311,0,0,0,0,2016-10-27,260,50,36,265.017,23,1,4,0,0
312,0,0,0,0,2016-10-27,291,31,40,265.017,25,1,1,1,0
313,0,0,0,0,2016-10-27,157,27,29,265.017,22,1,0,0,0
314,1,0,0,0,2016-10-28,179,26,30,265.017,19,3,0,0,5
315,1,0,0,0,2016-10-28,179,26,30,265.017,19,3,0,0,5
316,0,0,0,1,2016-10-29,118,13,50,265.017,31,1,1,0,1
317,1,0,0,0,2016-11-07,118,10,37,284.031,28,1,0,0,8
318,0,0,0,1,2016-11-07,248,25,47,284.031,32,1,2,1,2
319,1,0,0,0,2016-11-08,179,51,38,284.031,31,1,0,0,8
320,0,0,0,1,2016-11-11,260,50,36,284.031,23,1,4,0,3
321,0,0,0,1,2016-11-14,291,31,40,284.031,25,1,1,1,1
322,1,0,0,0,2016-11-14,378,49,36,284.031,21,1,2,4,8
323,1,0,0,0,2016-11-14,155,12,34,284.031,25,1,2,0,120
324,0,0,0,1,2016-11-14,235,20,43,284.031,38,1,1,0,8
325,0,0,0,0,2016-11-15,330,16,28,284.031,25,2,0,0,0
326,0,0,1,0,2016-11-16,235,11,37,284.031,29,3,1,1,1
327,1,0,0,0,2016-11-16,118,10,37,284.031,28,1,0,0,3
328,0,0,0,1,2016-11-17,235,11,37,284.031,29,3,1,1,2
329,0,0,0,1,2016-11-17,179,51,38,284.031,31,1,0,0,3
330,1,0,0,0,2016-11-18,246,25,41,284.031,23,1,0,0,8
331,1,0,0,0,2016-11-18,291,31,40,284.031,25,1,1,1,4
332,1,0,0,0,2016-11-21,246,25,41,284.031,23,1,0,0,8
333,0,0,0,1,2016-11-22,179,51,38,284.031,31,1,0,0,1
334,1,0,0,0,2016-11-23,260,50,36,284.031,23,1,4,0,8
335,0,1,0,0,2016-11-25,260,50,36,284.031,23,1,4,0,8
336,0,0,0,0,2016-11-25,378,49,36,284.031,21,1,2,4,0
337,0,0,0,0,2016-11-29,279,5,39,284.031,24,1,2,0,0
338,0,0,0,1,2016-11-24,179,51,38,284.031,31,1,0,0,1
339,1,0,0,0,2016-12-05,225,26,28,236.629,24,1,1,2,3
340,0,0,0,1,2016-12-05,179,51,38,236.629,31,1,0,0,2
341,0,0,0,1,2016-12-05,179,51,38,236.629,31,1,0,0,1
342,0,0,0,1,2016-12-05,235,11,37,236.629,29,3,1,1,3
343,0,0,0,1,2016-12-06,118,13,50,236.629,31,1,1,0,1
344,0,0,0,1,2016-12-09,260,50,36,236.629,23,1,4,0,4
345,1,0,0,0,2016-12-15,246,25,41,236.629,23,1,0,0,8
346,0,0,0,1,2016-12-15,179,51,38,236.629,31,1,0,0,1
347,0,0,0,1,2016-12-16,179,51,38,236.629,31,1,0,0,1
348,0,0,0,1,2016-12-20,179,26,30,236.629,19,3,0,0,1
349,0,0,0,1,2016-12-20,118,10,37,236.629,28,1,0,0,8
350,0,0,0,1,2016-12-22,235,11,37,236.629,29,3,1,1,2
351,0,0,0,1,2016-12-23,179,51,38,236.629,31,1,0,0,1
352,1,0,0,0,2016-12-20,235,20,43,236.629,38,1,1,0,8
353,1,0,0,0,2016-12-20,235,11,37,236.629,29,3,1,1,4
354,0,0,0,1,2016-12-21,260,50,36,236.629,23,1,4,0,8
355,0,0,0,1,2016-12-19,157,27,29,236.629,22,1,0,0,2
356,0,0,0,1,2016-12-19,179,51,38,236.629,31,1,0,0,3
357,0,0,1,0,2016-12-19,289,36,33,236.629,30,1,2,1,8
358,0,0,0,1,2017-01-04,225,26,28,330.061,24,1,1,2,5
359,0,0,1,0,2017-01-09,118,10,37,330.061,28,1,0,0,32
360,0,0,0,1,2017-01-09,155,12,34,330.061,25,1,2,0,2
361,1,0,0,0,2017-01-03,235,11,37,330.061,29,3,1,1,1
362,0,0,0,1,2017-01-03,155,12,34,330.061,25,1,2,0,4
363,0,0,0,1,2017-01-09,289,36,33,330.061,30,1,2,1,8
364,1,0,0,0,2017-01-11,291,31,40,330.061,25,1,1,1,8
365,0,0,0,1,2017-01-16,235,20,43,330.061,38,1,1,0,8
366,0,0,0,1,2017-01-16,118,13,50,330.061,31,1,1,0,4
367,0,0,0,1,2017-01-25,179,51,38,330.061,31,1,0,0,1
368,0,0,0,1,2017-01-27,179,51,38,330.061,31,1,0,0,1
369,0,0,0,1,2017-02-07,118,10,37,251.818,28,1,0,0,2
370,0,0,0,1,2017-02-01,179,51,38,251.818,31,1,0,0,3
371,1,0,0,0,2017-02-01,225,26,28,251.818,24,1,1,2,1
372,0,0,0,1,2017-02-03,289,36,33,251.818,30,1,2,1,3
373,0,0,0,1,2017-02-10,260,50,36,251.818,23,1,4,0,3
374,0,0,0,1,2017-02-17,179,51,38,251.818,31,1,0,0,3
375,0,0,0,1,2017-02-13,179,51,38,251.818,31,1,0,0,2
376,0,0,0,1,2017-02-15,179,51,38,251.818,31,1,0,0,3
377,1,0,0,0,2017-02-16,179,51,38,251.818,31,1,0,0,8
378,0,0,0,1,2017-02-16,246,25,41,251.818,23,1,0,0,8
379,0,0,0,1,2017-02-17,179,51,38,251.818,31,1,0,0,3
380,0,0,0,1,2017-02-13,189,29,33,251.818,25,1,2,2,8
381,0,0,0,1,2017-02-13,179,51,38,251.818,31,1,0,0,3

In [156]:
#Extract the month values
df_reason_mod['date'][0]

Timestamp('2015-07-07 00:00:00')

In [157]:
df_reason_mod['date'][0].month

7

In [158]:
#month list from 1-12 not 0-11
list_months = []
list_months

[]

In [159]:
for i in range(700):
    list_months.append(df_reason_mod['date'][i].month)

In [161]:
len(list_months)

700

In [162]:
#add month values into our dataframe

df_reason_mod['month_value'] = list_months
df_reason_mod.head()

,reason_1,reason_2,reason_3,reason_4,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

In [166]:
#extract the day of the week
#day of the week from 0-6 : 0 : Monday
df_reason_mod['date'][699].weekday()

3

In [167]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [168]:
df_reason_mod['day_of_the_week'] = df_reason_mod['date'].apply(date_to_weekday)

In [169]:
df_reason_mod.head()

,reason_1,reason_2,reason_3,reason_4,date,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value,day_of_the_week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [170]:
df_reason_mod = df_reason_mod.drop(['date'], axis =1)

In [171]:
df_reason_mod.head()

,reason_1,reason_2,reason_3,reason_4,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value,day_of_the_week
0,0,0,0,1,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,289,36,33,239.554,30,1,2,1,2,7,3

In [173]:
df_reason_mod['education'].unique()

array([1, 3, 2, 4])

In [174]:
df_reason_mod['education'].value_counts()

education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

- 1: High-school
- 2: Graduate
- 3: Postgraduate
- 4: a master or a doctor

In [175]:
#map the 2-4 into one
df_reason_mod['education'] = df_reason_mod['education'].map({
    1:0,
    2:1,
    3:1,
    4:1
})

In [176]:
df_reason_mod['education'].unique()

array([0, 1])

In [177]:
df_reason_mod['education'].value_counts()

education
0    583
1    117
Name: count, dtype: int64

In [178]:
type(df_reason_mod['transportation_expense'][0])

numpy.int64

In [179]:
type(df_reason_mod['distance_to_work'][0])

numpy.int64

In [180]:
type(df_reason_mod['age'][0])

numpy.int64

In [181]:
type(df_reason_mod['daily_work_load_average'][0])

numpy.float64

In [182]:
type(df_reason_mod['body_mass_index'][0])

numpy.int64

In [183]:
df_preprocessed = df_reason_mod.copy()
df_preprocessed.head()

,reason_1,reason_2,reason_3,reason_4,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value,day_of_the_week
0,0,0,0,1,289,36,33,239.554,30,0,2,1,4,7,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,0,7,1
2,0,0,0,1,179,51,38,239.554,31,0,0,0,2,7,2
3,1,0,0,0,279,5,39,239.554,24,0,2,0,4,7,3
4,0,0,0,1,289,36,33,239.554,30,0,2,1,2,7,3

In [186]:
#load clean data into csv file

df_preprocessed.to_csv('../data/preprocessed/clean_Absenteeism_data.csv', index=False)