In [6]:
from absenteeism_module import *

import warnings
warnings.filterwarnings('ignore')

In [7]:
pd.read_csv('../data/Absenteeism_new_data.csv').head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0

In [8]:
model = absenteeism_model('model', 'scaler')

In [9]:
# Load and clean the data
model.load_and_clean_data('../data/Absenteeism_new_data.csv')

In [10]:
model.predicted_outputs()

,reason_1,reason_2,reason_3,reason_4,month_value,transportation_expense,age,body_mass_index,education,children,pets,Probability,Prediction
0,0,0,0,1,6,179,30,19,1,0,0,0.140486,0
1,1,0,0,0,6,361,28,27,0,1,4,0.887699,1
2,0,0,0,1,6,155,34,25,0,2,0,0.291162,0
3,0,0,0,1,6,179,40,22,1,2,0,0.212681,0
4,1,0,0,0,6,155,34,25,0,2,0,0.742501,1
5,1,0,0,0,6,225,28,24,0,1,2,0.742556,1
6,1,0,0,0,6,118,46,25,0,2,0,0.555578,1
7,0,0,0,1,6,179,30,19,1,0,0,0.140486,0
8,0,0,0,1,6,118,37,28,0,0,0,0.128869,0
9,1,0,0,0,6,118,37,28,0,0,0,0.509438,1
10,0,0,0,1,6,378,36,21,0,2,4,0.493275,0
11,0,0,1,0,6,118,50,31,0,1,0,0.561730,1
12,0,0,1,0,6,233,31,21,1,1,8,0.325947,0
13,0,0,0,1,6,179,30,19,1,0,0,0.140486,0
14,0,0,0,0,6,235,48,33,0,1,5,0.059176,0
15,0,0,0,0,6,268,33,25,1,0,0,0.159130,0
16,0,0,1,0,6,118,50,31,0,1,0,0.561730,1
17,1,0,0,0,6,179,30,19,1,0,0,0.534321,1
18,0,0,0,1,6,291,40,25,0,1,1,0.400587,0
19,1,0,0,0,7,179,30,19,1,0,0,0.539603,1
20,0,0,0,1,7,118,37,28,0,0,0,0.131272,0
21,0,0,0,1,7,233,31,21,1,1,8,0.055233,0
22,1,0,0,0,7,118,37,28,0,0,0,0.514746,1
23,1,0,0,0,7,118,37,28,0,0,0,0.514746,1
24,0,0,0,1,7,233,31,21,1,1,8,0.055233,0
25,0,0,0,1,7,235,43,38,0,1,0,0.493712,0
26,0,0,1,0,7,233,31,21,1,1,8,0.330632,0
27,1,0,0,0,7,228,58,22,0,2,1,0.603642,1
28,0,0,0,1,7,118,37,28,0,0,0,0.131272,0
29,1,0,0,0,7,228,58,22,0,2,1,0.603642,1
30,0,0,0,1,7,189,33,25,0,2,2,0.268956,0
31,0,0,0,1,7,118,37,28,0,0,0,0.131272,0
32,0,0,0,1,7,361,28,27,0,1,4,0.534927,1
33,0,0,0,1,7,225,28,24,0,1,2,0.295626,0
34,1,0,0,0,7,369,31,25,0,3,0,0.974846,1
35,1,0,0,0,7,289,33,30,0,2,1,0.922668,1
36,1,0,0,0,7,235,37,29,1,1,1,0.756433,1
37,0,0,0,0,7,118,40,34,0,1,8,0.013720,0
38,0,0,0,0,7,231,39,35,0,2,2,0.232335,0
39,0,0,0,0,7,179,53,25,0,1,1,0.049374,0

In [11]:
import pymysql
from dotenv import load_dotenv
import os

In [12]:
# Load the .env file
load_dotenv()

connection = pymysql.connect(
    host=os.getenv('HOST'),
    port=int(os.getenv('PORT')),
    database=os.getenv('DATABASE_NAME'),
    user=os.getenv('USER_NAME'),
    password=os.getenv('PASSWORD')
)

In [13]:
cursor = connection.cursor()

In [14]:
query = 'SELECT * FROM predicted_outputs'

In [15]:
cursor.execute(query)

0

In [ ]:
#check point
df_new_obs = model.predicted_outputs()

In [ ]:
insert_query = 'INSERT INTO predicted_outputs (reason_1, reason_2, reason_3, reason_4, month_value, \
       transportation_expense, age', body_mass_index, education, \
       children, pets, Probability, Prediction) VALUES' \

In [21]:
insert_query = 'INSERT INTO predicted_outputs VALUES'

In [22]:
insert_query

'INSERT INTO predicted_outputs VALUES'

In [23]:
df_new_obs.shape

(40, 13)

In [24]:
df_new_obs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'month_value',
       'transportation_expense', 'age', 'body_mass_index', 'education',
       'children', 'pets', 'Probability', 'Prediction'], dtype=object)

In [29]:
for i in range(df_new_obs.shape[0]):
    insert_query += '('
    
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
        
    insert_query = insert_query[:-2] + '), '

insert_query

'INSERT INTO predicted_outputs VALUES(0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (1, 0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8876988476863031, 1), (0, 0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2911620278396245, 0), (0, 0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.2126809772321865, 0), (1, 0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7425011948388139, 1), (1, 0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.742555938009754, 1), (1, 0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5555776728084365, 1), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.1288685212020267, 0), (1, 0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5094379322178929, 1), (0, 0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4932750676303948, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (0, 0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.3259470605725858, 0), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.05917614037357819, 0), (0, 0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.15912955701377127, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (1, 0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5343209305342643, 1), (0, 0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.40058732188740714, 0), (1, 0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.539603066316963, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (0, 0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.4937124046738936, 0), (0, 0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3306318177510189, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.26895557993351316, 0), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.5349272245026853, 1), (0, 0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.2956256769350181, 0), (1, 0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.97484614926298, 1), (1, 0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9226684272426673, 1), (1, 0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7564328067762235, 1), (0, 0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.01372031760258728, 0), (0, 0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.23233472212392475, 0), (0, 0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.04937402427315664, 0);(0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (1, 0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8876988476863031, 1), (0, 0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2911620278396245, 0), (0, 0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.2126809772321865, 0), (1, 0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7425011948388139, 1), (1, 0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.742555938009754, 1), (1, 0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5555776728084365, 1), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.1288685212020267, 0), (1, 0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5094379322178929, 1), (0, 0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4932750676303948, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (0, 0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.3259470605725858, 0), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.05917614037357819, 0), (0, 0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.15912955701377127, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (1, 0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5343209305342643, 1), (0, 0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.40058732188740714, 0), (1, 0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.539603066316963, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (0, 0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.4937124046738936, 0), (0, 0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3306318177510189, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.26895557993351316, 0), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.5349272245026853, 1), (0, 0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.2956256769350181, 0), (1, 0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.97484614926298, 1), (1, 0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9226684272426673, 1), (1, 0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7564328067762235, 1), (0, 0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.01372031760258728, 0), (0, 0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.23233472212392475, 0), (0, 0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.04937402427315664, 0), '

In [30]:
insert_query = insert_query[:-2] + ';'
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (1, 0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8876988476863031, 1), (0, 0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2911620278396245, 0), (0, 0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.2126809772321865, 0), (1, 0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7425011948388139, 1), (1, 0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.742555938009754, 1), (1, 0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5555776728084365, 1), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.1288685212020267, 0), (1, 0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5094379322178929, 1), (0, 0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4932750676303948, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (0, 0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.3259470605725858, 0), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.05917614037357819, 0), (0, 0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.15912955701377127, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (1, 0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5343209305342643, 1), (0, 0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.40058732188740714, 0), (1, 0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.539603066316963, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (0, 0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.4937124046738936, 0), (0, 0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3306318177510189, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.26895557993351316, 0), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.5349272245026853, 1), (0, 0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.2956256769350181, 0), (1, 0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.97484614926298, 1), (1, 0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9226684272426673, 1), (1, 0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7564328067762235, 1), (0, 0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.01372031760258728, 0), (0, 0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.23233472212392475, 0), (0, 0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.04937402427315664, 0);(0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (1, 0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8876988476863031, 1), (0, 0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2911620278396245, 0), (0, 0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.2126809772321865, 0), (1, 0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7425011948388139, 1), (1, 0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.742555938009754, 1), (1, 0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5555776728084365, 1), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.1288685212020267, 0), (1, 0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5094379322178929, 1), (0, 0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4932750676303948, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (0, 0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.3259470605725858, 0), (0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (0, 0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.05917614037357819, 0), (0, 0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.15912955701377127, 0), (0, 0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.5617297845853221, 1), (1, 0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5343209305342643, 1), (0, 0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.40058732188740714, 0), (1, 0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.539603066316963, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (1, 0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.5147459866363477, 1), (0, 0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.0552327875144703, 0), (0, 0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.4937124046738936, 0), (0, 0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3306318177510189, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (1, 0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6036415507330546, 1), (0, 0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.26895557993351316, 0), (0, 0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.1312723605284315, 0), (0, 0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.5349272245026853, 1), (0, 0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.2956256769350181, 0), (1, 0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.97484614926298, 1), (1, 0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9226684272426673, 1), (1, 0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7564328067762235, 1), (0, 0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.01372031760258728, 0), (0, 0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.23233472212392475, 0), (0, 0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.04937402427315664, 0);'

In [31]:
cursor.execute(insert_query)

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0, 0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.1404863331990679, 0), (1, 0, 0, 0, 6, 36' at line 1")

In [32]:
cols = df_new_obs.columns.tolist()
insert_query = f"INSERT INTO predicted_outputs ({', '.join(cols)}) VALUES "

values_parts = []
for i in range(df_new_obs.shape[0]):
    row = df_new_obs.iloc[i]
    row_items = []
    for val in row:
        if pd.isna(val):
            row_items.append("NULL")
        elif isinstance(val, str):
            row_items.append("'" + val.replace("'", "''") + "'")
        else:
            row_items.append(str(val))
    values_parts.append("(" + ", ".join(row_items) + ")")

insert_query += ", ".join(values_parts) + ";"
cursor.execute(insert_query)
connection.commit()

In [ ]:
connection.commit()

##When we are ready to close conncetion with the workbench.
commit.close()